// ============================================================
// 01-extra. 소득공제 추가 항목 (데이터 확장)
// ============================================================
import type { TaxSavingItem } from "@/types/tax-database"

export const incomeDeductionsExtra: TaxSavingItem[] = [
  {
    id: "income_additional_personal_senior",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "추가공제",
    savingType: "deduction", targetAudience: ["employee", "senior"],
    name: "경로우대 추가공제",
    shortDescription: "70세 이상 부양가족 1인당 100만원 추가 공제",
    fullDescription: "기본공제 대상자 중 70세 이상인 경우 1인당 연 100만원 추가 공제.",
    tags: ["경로우대", "추가공제", "70세", "부양가족"],
    impactLevel: "low", maxDeductionAmount: 1_000_000, applicableRate: "1인당 100만원",
    requirements: [{ id: "r1", description: "기본공제 대상자 중 70세 이상", type: "age", value: "70세 이상", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제51조", effectiveDate: "2026-01-01" }],
    calculationParams: [{ id: "senior_count", label: "70세 이상 부양가족 수", type: "number", unit: "명", required: true }],
    calculationFormula: "추가공제 = 70세 이상 부양가족 수 × 100만원", urgency: "year_end", difficulty: "easy",
    steps: ["70세 이상 부양가족 확인", "연말정산 시 추가공제 체크"],
  },
  {
    id: "income_disabled_deduction",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "추가공제",
    savingType: "deduction", targetAudience: ["employee"],
    name: "장애인 추가공제",
    shortDescription: "장애인 부양가족 1인당 200만원 추가 공제",
    fullDescription: "기본공제 대상자 중 장애인에 해당하는 경우 1인당 연 200만원 추가 공제. 장애인복지법상 장애인, 국가유공자 상이자, 항시 치료를 요하는 중증환자 포함.",
    tags: ["장애인", "추가공제", "중증환자"],
    impactLevel: "medium", maxDeductionAmount: 2_000_000, applicableRate: "1인당 200만원",
    requirements: [{ id: "r1", description: "장애인 해당 부양가족", type: "other", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제51조", effectiveDate: "2026-01-01" }],
    calculationParams: [{ id: "disabled_count", label: "장애인 부양가족 수", type: "number", unit: "명", required: true }],
    calculationFormula: "추가공제 = 장애인 수 × 200만원", urgency: "year_end", difficulty: "easy",
    steps: ["장애인증명서 또는 중증환자 진단서 준비", "연말정산 시 제출"],
  },
  {
    id: "income_single_parent",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "추가공제",
    savingType: "deduction", targetAudience: ["employee"],
    name: "한부모 추가공제",
    shortDescription: "한부모 가정 연 100만원 추가 공제",
    fullDescription: "배우자가 없는 사람으로서 기본공제 대상자인 직계비속(자녀) 또는 입양자가 있는 경우 연 100만원 추가 공제. 부녀자공제와 중복 불가(유리한 것 선택).",
    tags: ["한부모", "추가공제", "부녀자공제"],
    impactLevel: "low", maxDeductionAmount: 1_000_000, applicableRate: "100만원",
    requirements: [{ id: "r1", description: "배우자 없이 직계비속 부양", type: "family", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제51조의2", effectiveDate: "2026-01-01" }],
    calculationParams: [], calculationFormula: "100만원 추가공제",
    urgency: "year_end", difficulty: "easy", steps: ["해당 여부 확인", "연말정산 시 체크"],
  },
  {
    id: "income_insurance_premium",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "보험료",
    savingType: "credit", targetAudience: ["employee"],
    name: "보장성 보험료 세액공제",
    shortDescription: "보장성 보험료 연 100만원 한도, 12% 세액공제",
    fullDescription: "근로자 본인 또는 부양가족을 피보험자로 하는 보장성 보험의 보험료에 대해 연 100만원 한도로 12% 세액공제. 장애인전용 보장성보험은 15%.",
    tags: ["보험료", "세액공제", "보장성보험"],
    impactLevel: "low", maxSavingAmount: 120_000, maxDeductionAmount: 1_000_000, applicableRate: "12% (장애인 15%)",
    requirements: [{ id: "r1", description: "보장성 보험 가입", type: "other", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제59조의4", effectiveDate: "2026-01-01" }],
    calculationParams: [{ id: "premium", label: "연간 보험료", type: "number", unit: "원", max: 1_000_000, required: true }],
    calculationFormula: "공제액 = min(보험료, 100만원) × 12%", urgency: "year_end", difficulty: "easy",
    steps: ["보장성 보험 가입 여부 확인", "연말정산 간소화 자동 반영"],
  },
  {
    id: "income_youth_savings",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "청년",
    savingType: "deduction", targetAudience: ["youth", "employee"],
    name: "청년형 장기펀드 소득공제",
    shortDescription: "청년 장기펀드 납입액 40% 소득공제 (연 600만원 한도)",
    fullDescription: "만 19~34세 청년이 청년형 장기집합투자증권저축에 가입하여 납입한 금액의 40%를 소득공제. 연 600만원 납입 한도, 최대 240만원 소득공제.",
    tags: ["청년", "장기펀드", "소득공제", "청년형"],
    impactLevel: "medium", maxDeductionAmount: 2_400_000, applicableRate: "납입액 40%",
    requirements: [
      { id: "r1", description: "만 19~34세", type: "age", value: "19~34세", critical: true },
      { id: "r2", description: "총급여 5,000만원 이하 또는 종합소득 3,800만원 이하", type: "income_limit", critical: true },
    ],
    legalBasis: [{ law: "조세특례제한법", article: "제91조의20", effectiveDate: "2026-01-01" }],
    calculationParams: [{ id: "fund_amount", label: "연 납입액", type: "number", unit: "원", max: 6_000_000, required: true }],
    calculationFormula: "공제액 = min(납입액, 600만원) × 40%", urgency: "year_round", difficulty: "easy",
    steps: ["청년형 장기펀드 가입", "연 납입 (월 50만원)", "3~5년 유지"],
    contentHook: { title: "청년이라면 무조건 가입! 연 240만원 소득공제 펀드", hook: "월 50만원으로 세금 환급 + 투자수익 동시에!", targetKeyword: "청년형 장기펀드 소득공제", estimatedViews: "medium" },
  },
  {
    id: "income_donation_political",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "기부금",
    savingType: "credit", targetAudience: ["all"],
    name: "정치자금 기부금 세액공제",
    shortDescription: "10만원까지 전액 세액공제, 초과분 15~25%",
    fullDescription: "정치자금법에 따른 기부금 10만원까지 전액(110/100) 세액공제. 10만원 초과분은 3천만원까지 15%, 3천만원 초과분 25% 세액공제.",
    tags: ["정치자금", "기부금", "세액공제"],
    impactLevel: "low", maxSavingAmount: 100_000, applicableRate: "10만원 전액, 초과 15~25%",
    requirements: [{ id: "r1", description: "정치자금법에 따른 기부", type: "other", critical: true }],
    legalBasis: [{ law: "조세특례제한법", article: "제76조", effectiveDate: "2026-01-01" }],
    calculationParams: [{ id: "amount", label: "정치자금 기부액", type: "number", unit: "원", required: true }],
    calculationFormula: "10만원 이하: 전액 공제. 초과분: 15~25%", urgency: "year_end", difficulty: "easy",
    steps: ["정당/후원회에 기부", "기부금 영수증 수령", "연말정산 반영"],
  },
  {
    id: "income_small_biz_mutual_aid",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "노란우산",
    savingType: "deduction", targetAudience: ["sole_proprietor", "freelancer"],
    name: "노란우산공제 소득공제",
    shortDescription: "소기업·소상공인 공제부금 연 최대 500만원 소득공제",
    fullDescription: "소기업·소상공인이 노란우산공제에 가입하여 납부한 공제부금에 대해 소득공제. 사업소득 4천만원 이하: 500만원, 4천만~1억: 300만원, 1억 초과: 200만원 한도.",
    tags: ["노란우산", "소상공인", "소득공제", "퇴직금"],
    impactLevel: "medium", maxDeductionAmount: 5_000_000, applicableRate: "소득별 200~500만원",
    requirements: [{ id: "r1", description: "소기업·소상공인", type: "business_type", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제51조의3", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "monthly_payment", label: "월 납입액", type: "number", unit: "원", max: 1_000_000, required: true },
      { id: "biz_income", label: "사업소득", type: "number", unit: "원", required: true },
    ],
    calculationFormula: "소득 4천만↓: 500만원 / 4천만~1억: 300만원 / 1억↑: 200만원 한도",
    urgency: "year_round", difficulty: "easy",
    steps: ["노란우산공제 가입 (중소기업중앙회)", "월 납입", "종합소득세 신고 시 소득공제 적용"],
    contentHook: { title: "소상공인 퇴직금 + 절세 동시에! 노란우산공제", hook: "매월 100만원씩 넣으면 연 500만원 소득공제!", targetKeyword: "노란우산공제 소득공제", estimatedViews: "medium" },
  },
]
