// ============================================================
// 02. 소득세 - 세액공제 항목 (의료비, 교육비, 기부금 등)
// ============================================================

import type { TaxSavingItem } from "@/types/tax-database"

export const incomeCredits: TaxSavingItem[] = [
  {
    id: "credit_medical",
    version: "2026.1",
    lastUpdated: "2026-01-01",
    category: "income",
    subcategory: "의료비",
    savingType: "credit",
    targetAudience: ["employee"],
    name: "의료비 세액공제",
    shortDescription: "총급여 3% 초과 의료비 15% 세액공제, 난임 30%",
    fullDescription: "근로자가 본인 및 부양가족을 위해 지출한 의료비 중 총급여의 3%를 초과하는 금액에 대해 15% 세액공제 (난임시술비 30%, 미숙아/선천성이상아 20%). 본인·65세이상·장애인·난임은 한도 없음, 그 외 700만원 한도.",
    tags: ["의료비", "세액공제", "난임", "건강보험"],
    impactLevel: "medium",
    maxDeductionAmount: 7_000_000,
    applicableRate: "15% (난임 30%)",
    requirements: [
      { id: "req_1", description: "총급여 3% 초과 의료비 지출", type: "income_limit", critical: true },
    ],
    legalBasis: [{ law: "소득세법", article: "제59조의4", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "total_salary", label: "총급여", type: "number", unit: "원", required: true },
      { id: "medical_expense", label: "의료비 총액", type: "number", unit: "원", required: true },
      { id: "infertility_expense", label: "난임시술비", type: "number", unit: "원", required: false },
    ],
    calculationFormula: "(의료비 - 총급여×3%) × 15% + 난임시술비 × 30%",
    urgency: "year_end",
    difficulty: "easy",
    steps: ["의료비 영수증 수집", "연말정산 간소화 자료 확인", "간소화 미반영분 직접 제출"],
  },

  {
    id: "credit_education",
    version: "2026.1",
    lastUpdated: "2026-01-01",
    category: "income",
    subcategory: "교육비",
    savingType: "credit",
    targetAudience: ["employee"],
    name: "교육비 세액공제",
    shortDescription: "교육비 15% 세액공제, 대학생 연 900만원 한도",
    fullDescription: "근로자 본인(한도 없음), 취학 전 아동·초중고(연 300만원), 대학생(연 900만원)의 교육비에 대해 15% 세액공제. 학원비(취학 전 아동만), 교복구입비(연 50만원) 포함.",
    tags: ["교육비", "세액공제", "대학등록금", "학원비"],
    impactLevel: "medium",
    maxDeductionAmount: 9_000_000,
    applicableRate: "15%",
    requirements: [
      { id: "req_1", description: "본인 또는 부양가족 교육비 지출", type: "other", critical: true },
    ],
    legalBasis: [{ law: "소득세법", article: "제59조의4", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "self_education", label: "본인 교육비", type: "number", unit: "원", required: false },
      { id: "child_education", label: "자녀 교육비", type: "number", unit: "원", required: false },
      { id: "child_type", label: "자녀 학교 단계", type: "select", options: [
        { label: "취학 전 (어린이집/유치원/학원)", value: "preschool" },
        { label: "초·중·고등학교", value: "k12" },
        { label: "대학교", value: "university" },
      ], required: false },
    ],
    calculationFormula: "min(교육비, 한도) × 15%",
    urgency: "year_end",
    difficulty: "easy",
    steps: ["교육기관 납부 영수증 확인", "연말정산 간소화 자료 조회", "학원비는 별도 영수증 제출 (취학 전)"],
  },

  {
    id: "credit_donation",
    version: "2026.1",
    lastUpdated: "2026-01-01",
    category: "income",
    subcategory: "기부금",
    savingType: "credit",
    targetAudience: ["employee", "freelancer", "sole_proprietor"],
    name: "기부금 세액공제",
    shortDescription: "1,000만원 이하 15%, 초과분 30% 세액공제",
    fullDescription: "법정기부금(국가, 지자체 등), 지정기부금(종교단체, 사회복지법인 등)에 대해 세액공제를 받을 수 있습니다. 1,000만원 이하 15%, 1,000만원 초과분 30% 공제.",
    tags: ["기부금", "세액공제", "종교기부", "사회공헌"],
    impactLevel: "medium",
    applicableRate: "15% (1천만원↓) / 30% (1천만원↑)",
    requirements: [
      { id: "req_1", description: "기부금 영수증 보유", type: "other", critical: true },
    ],
    legalBasis: [{ law: "소득세법", article: "제59조의4", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "donation_amount", label: "기부금 총액", type: "number", unit: "원", required: true },
      { id: "donation_type", label: "기부금 유형", type: "select", options: [
        { label: "법정기부금 (국가, 지자체)", value: "legal" },
        { label: "지정기부금 (종교)", value: "religious" },
        { label: "지정기부금 (비종교)", value: "designated" },
        { label: "정치자금기부금", value: "political" },
      ], required: true },
    ],
    calculationFormula: "min(기부금, 1천만) × 15% + max(기부금-1천만, 0) × 30%",
    urgency: "year_end",
    difficulty: "easy",
    steps: ["기부금 영수증 발급 요청", "연말정산 간소화 자료 확인", "누락 시 직접 입력"],
  },

  {
    id: "credit_child",
    version: "2026.1",
    lastUpdated: "2026-01-01",
    category: "income",
    subcategory: "자녀",
    savingType: "credit",
    targetAudience: ["parent", "employee"],
    name: "자녀 세액공제 (2026 확대)",
    shortDescription: "자녀 1명 25만원, 2명 55만원, 3명+ 추가 40만원",
    fullDescription: "8세 이상 자녀에 대해 세액공제. 2025년 귀속부터 1명 25만원(종전 15만원), 2명 55만원(종전 35만원), 3명 이상 시 추가 1인당 40만원(종전 30만원)으로 확대.",
    tags: ["자녀", "세액공제", "양육", "출산"],
    impactLevel: "low",
    maxSavingAmount: 950_000, // 3명 기준
    applicableRate: "1명 25만 / 2명 55만 / 3명+ 추가 40만",
    requirements: [
      { id: "req_1", description: "8세 이상 자녀", type: "age", value: "8세 이상", critical: true },
    ],
    legalBasis: [{ law: "소득세법", article: "제59조의2", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "children_count", label: "8세 이상 자녀 수", type: "number", unit: "명", min: 1, max: 10, required: true },
    ],
    calculationFormula: "1명: 25만 / 2명: 55만 / 3명 이상: 55만 + (자녀수-2) × 40만",
    urgency: "year_end",
    difficulty: "easy",
    steps: ["자녀 수 확인", "연말정산 시 자동 적용"],
  },

  {
    id: "credit_childcare_benefit",
    version: "2026.1",
    lastUpdated: "2026-01-01",
    category: "income",
    subcategory: "출산/보육",
    savingType: "exemption",
    targetAudience: ["parent", "employee"],
    name: "출산·보육수당 비과세 확대",
    shortDescription: "6세 이하 자녀 보육수당 자녀 1명당 월 20만원 비과세",
    fullDescription: "근로자 본인이나 배우자의 출산 및 6세 이하 자녀 보육 관련 급여 비과세 한도가 기존 월 20만원(총합)에서 자녀 1명당 월 20만원으로 확대. 자녀 2명이면 월 40만원 비과세.",
    tags: ["보육수당", "비과세", "출산", "육아"],
    impactLevel: "medium",
    applicableRate: "자녀 1명당 월 20만원 비과세",
    requirements: [
      { id: "req_1", description: "6세 이하 자녀 보유", type: "age", value: "6세 이하", critical: true },
      { id: "req_2", description: "회사에서 보육수당 지급", type: "other", critical: true },
    ],
    legalBasis: [{ law: "소득세법", article: "제12조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "children_under6", label: "6세 이하 자녀 수", type: "number", unit: "명", required: true },
    ],
    calculationFormula: "비과세 한도 = 자녀 수 × 20만원/월 × 12개월",
    urgency: "year_round",
    difficulty: "easy",
    steps: ["회사 인사팀에 보육수당 비과세 신청", "자녀 출생증명서 또는 주민등록등본 제출"],
  },
]
