// ============================================================
// 02. 소득세 - 세액공제 항목 (의료비, 교육비, 기부금 등)
// ============================================================

import type { TaxSavingItem } from "@/types/tax-database"

export const incomeCredits: TaxSavingItem[] = [
  {
    id: "credit_medical",
    version: "2026.1",
    lastUpdated: "2026-01-01",
    category: "income",
    subcategory: "의료비",
    savingType: "credit",
    targetAudience: ["employee"],
    name: "의료비 세액공제",
    shortDescription: "총급여 3% 초과 의료비 15% 세액공제, 난임 30%",
    fullDescription: "근로자가 본인 및 부양가족을 위해 지출한 의료비 중 총급여의 3%를 초과하는 금액에 대해 15% 세액공제 (난임시술비 30%, 미숙아/선천성이상아 20%). 본인·65세이상·장애인·난임은 한도 없음, 그 외 700만원 한도.",
    tags: ["의료비", "세액공제", "난임", "건강보험"],
    impactLevel: "medium",
    maxDeductionAmount: 7_000_000,
    applicableRate: "15% (난임 30%)",
    requirements: [
      { id: "req_1", description: "총급여 3% 초과 의료비 지출", type: "income_limit", critical: true },
    ],
    legalBasis: [{ law: "소득세법", article: "제59조의4", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "total_salary", label: "총급여", type: "number", unit: "원", required: true },
      { id: "medical_expense", label: "의료비 총액", type: "number", unit: "원", required: true },
      { id: "infertility_expense", label: "난임시술비", type: "number", unit: "원", required: false },
    ],
    calculationFormula: "(의료비 - 총급여×3%) × 15% + 난임시술비 × 30%",
    urgency: "year_end",
    difficulty: "easy",
    steps: ["의료비 영수증 수집", "연말정산 간소화 자료 확인", "간소화 미반영분 직접 제출"],
    warnings: [
      "총급여 3% 초과분만 공제 대상 — 총급여가 높을수록 공제 적용 문턱도 높아짐",
      "미용·성형 수술비, 건강증진 목적 의약품 구입비는 공제 불가",
      "안경·콘택트렌즈 구입비는 1인당 연 50만원 한도, 간소화에 미반영 시 영수증 직접 제출 필요",
      "본인·65세 이상·장애인·난임시술비는 한도 없음 — 일반 부양가족(700만원 한도)과 구분 필요",
    ],
    practicalCases: [
      {
        title: "총급여 4,000만원 직장인, 의료비 200만원 지출",
        situation: "본인 입원비 150만원 + 부모 병원비 50만원, 총급여 4,000만원",
        calculation: "공제 대상 = 200만 - (4,000만 × 3%) = 200만 - 120만 = 80만원. 80만원 × 15% = 12만원 세액공제",
        result: "연말정산 12만원 환급",
        taxSaved: 120_000,
      },
      {
        title: "난임시술비 지출 맞벌이 부부",
        situation: "난임시술비 300만원 지출, 총급여 5,000만원",
        calculation: "난임시술비 300만원 × 30% = 90만원 세액공제 (한도 없음)",
        result: "연말정산 90만원 환급",
        taxSaved: 900_000,
      },
    ],
  },

  {
    id: "credit_education",
    version: "2026.1",
    lastUpdated: "2026-01-01",
    category: "income",
    subcategory: "교육비",
    savingType: "credit",
    targetAudience: ["employee"],
    name: "교육비 세액공제",
    shortDescription: "교육비 15% 세액공제, 대학생 연 900만원 한도",
    fullDescription: "근로자 본인(한도 없음), 취학 전 아동·초중고(연 300만원), 대학생(연 900만원)의 교육비에 대해 15% 세액공제. 학원비(취학 전 아동만), 교복구입비(연 50만원) 포함.",
    tags: ["교육비", "세액공제", "대학등록금", "학원비"],
    impactLevel: "medium",
    maxDeductionAmount: 9_000_000,
    applicableRate: "15%",
    requirements: [
      { id: "req_1", description: "본인 또는 부양가족 교육비 지출", type: "other", critical: true },
    ],
    legalBasis: [{ law: "소득세법", article: "제59조의4", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "self_education", label: "본인 교육비", type: "number", unit: "원", required: false },
      { id: "child_education", label: "자녀 교육비", type: "number", unit: "원", required: false },
      { id: "child_type", label: "자녀 학교 단계", type: "select", options: [
        { label: "취학 전 (어린이집/유치원/학원)", value: "preschool" },
        { label: "초·중·고등학교", value: "k12" },
        { label: "대학교", value: "university" },
      ], required: false },
    ],
    calculationFormula: "min(교육비, 한도) × 15%",
    urgency: "year_end",
    difficulty: "easy",
    steps: ["교육기관 납부 영수증 확인", "연말정산 간소화 자료 조회", "학원비는 별도 영수증 제출 (취학 전)"],
    warnings: [
      "대학원 교육비는 본인만 공제 가능 — 부양가족의 대학원비는 공제 불가",
      "초·중·고 학원비·과외비는 공제 불가 — 취학 전 아동 학원비만 허용",
      "소득 있는 자녀의 교육비는 본인이 직접 지출한 경우만 공제 (소득 있는 자녀는 기본공제 대상 제외 주의)",
      "외국 교육기관 교육비는 원칙적으로 공제 불가 (국내 국제학교 일부 예외)",
    ],
    practicalCases: [
      {
        title: "대학생 자녀 등록금 연 900만원",
        situation: "부양하는 대학생 자녀 등록금 연 900만원 납부",
        calculation: "min(900만, 900만) × 15% = 135만원 세액공제",
        result: "연말정산 135만원 환급",
        taxSaved: 1_350_000,
      },
      {
        title: "본인 직업훈련비 + 자녀 유치원비",
        situation: "본인 직업훈련 수강료 200만원 + 6세 자녀 유치원비 300만원",
        calculation: "본인 200만원(한도 없음) + 자녀 min(300만, 300만한도) = 500만원. 500만원 × 15% = 75만원",
        result: "연말정산 75만원 환급",
        taxSaved: 750_000,
      },
    ],
  },

  {
    id: "credit_donation",
    version: "2026.1",
    lastUpdated: "2026-01-01",
    category: "income",
    subcategory: "기부금",
    savingType: "credit",
    targetAudience: ["employee", "freelancer", "sole_proprietor"],
    name: "기부금 세액공제",
    shortDescription: "1,000만원 이하 15%, 초과분 30% 세액공제",
    fullDescription: "법정기부금(국가, 지자체 등), 지정기부금(종교단체, 사회복지법인 등)에 대해 세액공제를 받을 수 있습니다. 1,000만원 이하 15%, 1,000만원 초과분 30% 공제.",
    tags: ["기부금", "세액공제", "종교기부", "사회공헌"],
    impactLevel: "medium",
    applicableRate: "15% (1천만원↓) / 30% (1천만원↑)",
    requirements: [
      { id: "req_1", description: "기부금 영수증 보유", type: "other", critical: true },
    ],
    legalBasis: [{ law: "소득세법", article: "제59조의4", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "donation_amount", label: "기부금 총액", type: "number", unit: "원", required: true },
      { id: "donation_type", label: "기부금 유형", type: "select", options: [
        { label: "법정기부금 (국가, 지자체)", value: "legal" },
        { label: "지정기부금 (종교)", value: "religious" },
        { label: "지정기부금 (비종교)", value: "designated" },
        { label: "정치자금기부금", value: "political" },
      ], required: true },
    ],
    calculationFormula: "min(기부금, 1천만) × 15% + max(기부금-1천만, 0) × 30%",
    urgency: "year_end",
    difficulty: "easy",
    steps: ["기부금 영수증 발급 요청", "연말정산 간소화 자료 확인", "누락 시 직접 입력"],
    warnings: [
      "지정기부금(비종교)은 소득금액의 30% 한도, 종교단체는 10% 한도 — 한도 초과분은 다음 연도로 이월 가능(최대 10년)",
      "기부금 영수증은 기부금품법 요건에 맞는 적격 영수증이어야 함 — 간이영수증 불가",
      "사실상 기부지만 반대급부(물품·서비스 수령)가 있는 경우 공제 불가",
      "법인에 대한 기부는 법정·지정기부금 유형 확인 필수 — 미등록 단체 기부는 공제 불가",
    ],
    practicalCases: [
      {
        title: "종교단체 연 200만원 기부",
        situation: "교회 헌금 연 200만원, 총급여 5,000만원(소득금액 약 3,500만원)",
        calculation: "종교단체 한도 = 3,500만 × 10% = 350만원. 200만원 전액 한도 내. 200만원 × 15% = 30만원 세액공제",
        result: "연말정산 30만원 환급",
        taxSaved: 300_000,
      },
      {
        title: "사회복지단체 500만원 + 1,000만원 초과 기부",
        situation: "비종교 지정기부금 1,500만원 기부, 소득금액 5,000만원",
        calculation: "1,000만원 × 15% + 500만원 × 30% = 150만원 + 150만원 = 300만원 세액공제",
        result: "연말정산 300만원 환급",
        taxSaved: 3_000_000,
      },
    ],
  },

  {
    id: "credit_child",
    version: "2026.1",
    lastUpdated: "2026-01-01",
    category: "income",
    subcategory: "자녀",
    savingType: "credit",
    targetAudience: ["parent", "employee"],
    name: "자녀 세액공제 (2026 확대)",
    shortDescription: "자녀 1명 25만원, 2명 55만원, 3명+ 추가 40만원",
    fullDescription: "8세 이상 자녀에 대해 세액공제. 2025년 귀속부터 1명 25만원(종전 15만원), 2명 55만원(종전 35만원), 3명 이상 시 추가 1인당 40만원(종전 30만원)으로 확대.",
    tags: ["자녀", "세액공제", "양육", "출산"],
    impactLevel: "low",
    maxSavingAmount: 950_000, // 3명 기준
    applicableRate: "1명 25만 / 2명 55만 / 3명+ 추가 40만",
    requirements: [
      { id: "req_1", description: "8세 이상 자녀", type: "age", value: "8세 이상", critical: true },
    ],
    legalBasis: [{ law: "소득세법", article: "제59조의2", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "children_count", label: "8세 이상 자녀 수", type: "number", unit: "명", min: 1, max: 10, required: true },
    ],
    calculationFormula: "1명: 25만 / 2명: 55만 / 3명 이상: 55만 + (자녀수-2) × 40만",
    urgency: "year_end",
    difficulty: "easy",
    steps: ["자녀 수 확인", "연말정산 시 자동 적용"],
    warnings: [
      "만 8세 기준은 해당 과세연도 12월 31일 기준 — 당해연도 8세 생일이면 공제 대상",
      "출산·입양 세액공제와 중복 적용 불가 — 출산 연도에는 출산 공제가 더 유리할 수 있음",
      "기본공제 대상 자녀여야 함 — 소득 있는 자녀(소득금액 100만원 초과)는 제외",
      "이혼·별거 시 실제 기본공제를 신청하는 부모 중 한 명만 공제 가능 — 중복 신청 불가",
    ],
    practicalCases: [
      {
        title: "자녀 2명 부양 직장인",
        situation: "8세, 12세 자녀 2명, 총급여 5,000만원",
        calculation: "2명 → 55만원 세액공제",
        result: "연말정산 55만원 직접 차감",
        taxSaved: 550_000,
      },
      {
        title: "자녀 3명 다자녀 가구",
        situation: "9세, 13세, 16세 자녀 3명 부양",
        calculation: "55만원 + 40만원(3번째) = 95만원 세액공제",
        result: "연말정산 95만원 직접 차감",
        taxSaved: 950_000,
      },
    ],
  },

  {
    id: "credit_childcare_benefit",
    version: "2026.1",
    lastUpdated: "2026-01-01",
    category: "income",
    subcategory: "출산/보육",
    savingType: "exemption",
    targetAudience: ["parent", "employee"],
    name: "출산·보육수당 비과세 확대",
    shortDescription: "6세 이하 자녀 보육수당 자녀 1명당 월 20만원 비과세",
    fullDescription: "근로자 본인이나 배우자의 출산 및 6세 이하 자녀 보육 관련 급여 비과세 한도가 기존 월 20만원(총합)에서 자녀 1명당 월 20만원으로 확대. 자녀 2명이면 월 40만원 비과세.",
    tags: ["보육수당", "비과세", "출산", "육아"],
    impactLevel: "medium",
    applicableRate: "자녀 1명당 월 20만원 비과세",
    requirements: [
      { id: "req_1", description: "6세 이하 자녀 보유", type: "age", value: "6세 이하", critical: true },
      { id: "req_2", description: "회사에서 보육수당 지급", type: "other", critical: true },
    ],
    legalBasis: [{ law: "소득세법", article: "제12조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "children_under6", label: "6세 이하 자녀 수", type: "number", unit: "명", required: true },
    ],
    calculationFormula: "비과세 한도 = 자녀 수 × 20만원/월 × 12개월",
    urgency: "year_round",
    difficulty: "easy",
    steps: ["회사 인사팀에 보육수당 비과세 신청", "자녀 출생증명서 또는 주민등록등본 제출"],
    warnings: [
      "회사가 보육수당을 급여 항목으로 설정하지 않은 경우 비과세 혜택 불가 — 인사팀 사전 확인 필수",
      "자녀 1명당 월 20만원이 한도이므로 실제 지급액이 초과하면 초과분은 과세 대상",
      "6세 이하 기준은 해당 연도 12월 31일 기준 — 연중 7세가 된 자녀는 해당 연도 비과세 불가",
      "배우자의 회사에서도 동일 자녀에 대해 비과세 수령 가능 — 부부 각각 적용 가능",
    ],
    practicalCases: [
      {
        title: "6세 이하 자녀 1명, 보육수당 월 20만원 수령",
        situation: "회사에서 보육수당 월 20만원 지급, 자녀 4세",
        calculation: "20만원 × 12개월 = 240만원 비과세. 세율 15% 기준 36만원 세금 절감",
        result: "연 240만원 급여가 과세 대상에서 제외",
        taxSaved: 360_000,
      },
      {
        title: "맞벌이 부부, 자녀 2명 (5세, 3세)",
        situation: "부부 각각 보육수당 월 40만원 수령 (자녀 2명 × 20만원)",
        calculation: "부부 각각 40만원 × 12개월 = 각 480만원 비과세. 합산 960만원 비과세",
        result: "가구 기준 연 960만원 비과세 혜택",
        taxSaved: 1_440_000,
      },
    ],
  },
]
