// ============================================================
// 03. 사업소득세 절세 (개인사업자/프리랜서)
// ============================================================

import type { TaxSavingItem } from "@/types/tax-database"

export const businessTax: TaxSavingItem[] = [
  {
    id: "biz_expense_optimization",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "경비처리",
    savingType: "deduction", targetAudience: ["sole_proprietor", "freelancer"],
    name: "필요경비 최적화",
    shortDescription: "사업 관련 지출을 경비로 처리하여 과세소득 감소",
    fullDescription: "사업과 직접 관련된 지출(임차료, 인건비, 소모품비, 차량유지비, 통신비, 접대비 등)을 필요경비로 인정받아 종합소득 과세표준을 낮춥니다. 사업용 신용카드/현금영수증 사용이 핵심.",
    tags: ["경비처리", "필요경비", "사업자", "종합소득세"],
    impactLevel: "high", applicableRate: "소득세율 6~45%만큼 절세",
    requirements: [{ id: "req_1", description: "사업자등록 필수", type: "business_type", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제27조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "revenue", label: "연간 매출", type: "number", unit: "원", required: true },
      { id: "expenses", label: "필요경비 합계", type: "number", unit: "원", required: true },
    ],
    calculationFormula: "과세소득 = 매출 - 필요경비. 경비 증가 → 과세소득 감소 → 세율구간 하락",
    urgency: "year_round", difficulty: "medium",
    steps: ["사업용 카드 등록", "모든 사업 지출 영수증 수집", "접대비 한도 확인", "종합소득세 신고 시 경비 반영"],
    contentHook: { title: "프리랜서 경비처리 A to Z, 세금 절반으로!", hook: "카페 커피도 경비? 되는 것 안 되는 것 총정리", targetKeyword: "프리랜서 경비처리", estimatedViews: "high" },
    warnings: [
      "증빙서류(세금계산서, 카드영수증, 현금영수증) 없는 경비는 원칙적으로 불인정",
      "접대비는 연간 한도 초과분 경비 불인정 (중소기업 기본한도 2,400만원 + 수입금액 비율)",
      "가사 겸용 지출은 사업 관련 비율만 인정 — 과도한 공제는 세무조사 대상",
      "부당과소신고 시 신고불성실가산세 40% + 납부지연가산세 별도 부과",
      "현금 거래 시 현금영수증 의무 미발행 시 미발행 금액의 20% 가산세",
    ],
    practicalCases: [
      {
        title: "연매출 5천만원 프리랜서의 경비처리 최적화",
        situation: "IT 프리랜서, 연매출 5,000만원. 사업용 카드 사용 전: 경비 500만원. 카드 등록 및 경비 정리 후: 경비 1,500만원 확인.",
        calculation: "경비 500만원 → 과세소득 4,500만원 → 세율 24% → 세액 약 648만원\n경비 1,500만원 → 과세소득 3,500만원 → 세율 15% → 세액 약 390만원",
        result: "경비 1,000만원 추가 인정으로 세금 약 258만원 절감",
        taxSaved: 2580000,
      },
      {
        title: "1인 디자이너 사업용 카드 등록 효과",
        situation: "그래픽 디자이너, 연매출 3,000만원. 개인카드로 소프트웨어 구독료, 장비, 교육비 지출. 사업용 카드 미등록 상태.",
        calculation: "사업용 카드 등록 후 경비 800만원 추가 확인\n과세소득 800만원 감소 → 세율 15% 구간 → 절세액 = 800만원 × 15% = 120만원",
        result: "사업용 카드 등록 한 번으로 연 120만원 절세",
        taxSaved: 1200000,
      },
    ],
  },
  {
    id: "biz_simplified_bookkeeping",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "장부/기장",
    savingType: "deduction", targetAudience: ["sole_proprietor", "freelancer"],
    name: "간편장부 vs 복식부기 선택 전략",
    shortDescription: "기장 방식에 따라 세액공제 20% 추가 가능",
    fullDescription: "복식부기 의무자가 아닌 사업자가 자발적으로 복식부기로 기장하면 기장세액공제 20%(100만원 한도)를 추가로 받을 수 있습니다. 반대로 기장 의무 불이행 시 20% 가산세.",
    tags: ["간편장부", "복식부기", "기장세액공제", "무기장가산세"],
    impactLevel: "medium", applicableRate: "기장세액공제 20% (100만원 한도)",
    requirements: [{ id: "req_1", description: "간편장부 대상자가 복식부기 자발 선택", type: "other", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제56조의2", effectiveDate: "2026-01-01" }],
    calculationParams: [{ id: "tax_amount", label: "산출세액", type: "number", unit: "원", required: true }],
    calculationFormula: "기장세액공제 = min(산출세액 × 20%, 100만원)",
    urgency: "quarterly", difficulty: "medium",
    steps: ["기장 의무 구분 확인 (전년도 수입 기준)", "복식부기 기장 또는 세무사 위임", "종합소득세 신고 시 기장세액공제 신청"],
    warnings: [
      "기장 의무자가 무기장 신고 시 산출세액의 20% 무기장가산세 부과",
      "간편장부 대상자 기준은 전년도 수입금액으로 판단 — 업종별 기준 상이",
      "복식부기 의무자가 간편장부로 신고 시 무기장가산세 + 기장세액공제 불가",
      "기장세액공제는 비사업소득이 있는 경우 안분 계산 필요",
      "세무사 위임 시 기장세액공제는 사업자 본인 명의 신고분에만 적용",
    ],
    practicalCases: [
      {
        title: "간편장부 대상 프리랜서의 자발적 복식부기 전환",
        situation: "번역가 프리랜서, 전년도 수입 4,500만원으로 간편장부 대상. 세무사에게 복식부기 기장 의뢰. 산출세액 500만원.",
        calculation: "기장세액공제 = min(500만원 × 20%, 100만원) = 100만원\n실질 납부세액 = 500만원 - 100만원 = 400만원",
        result: "복식부기 자발 선택으로 세액공제 100만원 절감. 세무사 비용 60만원 제외해도 순 절세 40만원",
        taxSaved: 1000000,
      },
      {
        title: "무기장 신고로 인한 가산세 사례",
        situation: "소매업 개인사업자, 전년도 수입 8,000만원(복식부기 의무자). 장부 미작성 후 추계신고. 산출세액 900만원.",
        calculation: "무기장가산세 = 900만원 × 20% = 180만원\n복식부기 기장 시 기장세액공제 = min(900만원 × 20%, 100만원) = 100만원\n가산세 회피 + 공제 합산 절감액 = 280만원",
        result: "장부 미작성으로 280만원 손실. 세무사 기장료 월 15만원(연 180만원)이어도 기장이 유리",
        taxSaved: 2800000,
      },
    ],
  },
  {
    id: "biz_to_corp_conversion",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "법인전환",
    savingType: "structure", targetAudience: ["sole_proprietor"],
    name: "개인사업자 → 법인 전환 절세",
    shortDescription: "소득 일정 수준 이상 시 법인 전환으로 세율 차이 활용",
    fullDescription: "개인사업자의 종합소득세 최고세율은 45%인 반면 법인세는 최고 25%(2026). 연 소득이 약 8,800만원을 넘으면 법인 전환이 유리할 수 있습니다. 대표이사 급여 설계, 배당소득 분리과세와 결합하면 절세 극대화.",
    tags: ["법인전환", "개인사업자", "법인세", "소득세", "세율비교"],
    impactLevel: "very_high", applicableRate: "소득세 최고 45% → 법인세 10/20/22/25%",
    requirements: [
      { id: "req_1", description: "연 과세소득 8,800만원 이상 권장", type: "income_limit", value: "8,800만원 이상", critical: false },
    ],
    legalBasis: [
      { law: "소득세법", article: "제55조", effectiveDate: "2026-01-01" },
      { law: "법인세법", article: "제55조", effectiveDate: "2026-01-01" },
    ],
    calculationParams: [
      { id: "annual_income", label: "연간 사업소득", type: "number", unit: "원", required: true },
      { id: "desired_salary", label: "대표이사 희망 급여 (법인 전환 시)", type: "number", unit: "원", required: false },
    ],
    calculationFormula: "개인세금 vs (법인세 + 대표급여 소득세 + 배당세) 비교",
    urgency: "long_term", difficulty: "hard",
    steps: ["개인 vs 법인 세부담 시뮬레이션", "법인 설립 (자본금, 정관)", "사업 포괄양수도 또는 현물출자", "대표이사 급여 최적 설계", "배당 시점/금액 계획"],
    contentHook: { title: "연매출 1억 넘으면 법인 전환? 시뮬레이션 결과 공개", hook: "같은 매출, 세금 1천만원 차이나는 이유!", targetKeyword: "개인사업자 법인전환 절세", estimatedViews: "high" },
    warnings: [
      "법인 전환 후 대표이사 급여를 과도하게 낮추면 사회보험료 절감 효과가 줄고 노후 대비 취약",
      "법인 설립 초기 비용(등록면허세, 법무사 비용, 자본금 등) 및 유지비용(법인세 신고, 감사 등) 고려 필요",
      "개인사업 자산을 법인에 양도 시 양도소득세 및 취득세 발생 가능 — 조세특례(포괄양수도) 검토 필수",
      "법인의 잉여금을 개인이 사용하려면 배당 또는 급여로만 가능 — 임의 인출 시 가지급금 처리 및 인정이자 과세",
      "법인 전환 후 5년 이내 폐업 또는 주식 양도 시 취득세 감면분 추징 가능",
    ],
    practicalCases: [
      {
        title: "연소득 1.5억 개인사업자의 법인 전환 절세 효과",
        situation: "온라인 쇼핑몰 사업자, 연 사업소득 1억 5,000만원. 법인 전환 후 대표이사 급여 7,000만원 설계, 나머지는 법인 유보.",
        calculation: "개인 시: 과세소득 1.5억 → 세율 38% → 소득세 약 3,706만원\n법인 전환 시: 법인세(1.5억-7천만 = 8천만원 × 9%) 720만원 + 대표급여 소득세(7천만원 기준) 약 1,106만원 = 합계 약 1,826만원",
        result: "법인 전환으로 연간 약 1,880만원 절세 (세무사 자문 필수)",
        taxSaved: 18800000,
      },
      {
        title: "법인 가지급금으로 인한 인정이자 과세 사례",
        situation: "법인 대표가 개인 용도로 법인 자금 3,000만원을 '일시 차용'. 가지급금 처리됨.",
        calculation: "인정이자율(2026년 기준 4.6%) 적용\n인정이자 = 3,000만원 × 4.6% = 138만원 → 법인 익금산입, 대표 상여 처리\n대표 소득세(세율 35% 가정) = 138만원 × 35% = 약 48만원 추가 과세",
        result: "법인 자금 무단 인출은 인정이자 과세 + 법인세 손금 불산입 이중 불이익 발생",
        taxSaved: -480000,
      },
    ],
  },
]
