// ============================================================
// 04-extra. 법인세 절세 추가 항목
// ============================================================
import type { TaxSavingItem } from "@/types/tax-database"

export const corporateTaxExtra: TaxSavingItem[] = [
  {
    id: "corp_investment_credit",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "corporate", subcategory: "투자세액공제",
    savingType: "credit", targetAudience: ["corporation"],
    name: "통합투자세액공제",
    shortDescription: "사업용 자산 투자액의 1~12% 세액공제",
    fullDescription: "기계장치, 시설 등 사업용 유형자산에 투자한 경우 기본공제(중소 10%, 대기업 1%) + 증가분 추가공제(3%). 국가전략기술 투자는 최대 25%.",
    tags: ["투자세액공제", "기계장치", "시설투자", "국가전략기술"],
    impactLevel: "high", applicableRate: "중소 10%+3% / 대기업 1%+3%",
    requirements: [{ id: "r1", description: "사업용 유형자산 투자", type: "other", critical: true }],
    legalBasis: [{ law: "조세특례제한법", article: "제24조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "invest_amount", label: "투자금액", type: "number", unit: "원", required: true },
      { id: "prior_year_invest", label: "전년도 투자금액", type: "number", unit: "원", required: false },
    ],
    calculationFormula: "기본: 투자액 × 10%(중소). 추가: (당기-직전3년평균) × 3%", urgency: "year_round", difficulty: "medium",
    steps: ["투자 자산 목록 정리", "기본+추가 공제 계산", "법인세 신고 시 세액공제 신청"],
    contentHook: { title: "설비투자하면 세금 10% 돌려받는다! 통합투자세액공제", hook: "1억 기계 사면 1,300만원 세금 환급!", targetKeyword: "통합투자세액공제 중소기업", estimatedViews: "medium" },
  },
  {
    id: "corp_dividend_timing",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "corporate", subcategory: "배당전략",
    savingType: "split", targetAudience: ["business_owner", "corporation"],
    name: "배당 시점·금액 최적화 (2026 분리과세 활용)",
    shortDescription: "2026년 배당소득 분리과세 신설로 배당 전략 재설계",
    fullDescription: "2026년부터 배당소득 분리과세(2천만↓ 15.4%, 2천만~3억 22%, 3억~50억 27.5%) 도입. 법인세를 약간 더 내더라도 이익잉여금을 배당으로 가져올 때 세금이 대폭 줄어듦. 종합과세(최대 49.5%) 대비 최대 22%p 절세.",
    tags: ["배당", "분리과세", "이익잉여금", "법인", "주주"],
    impactLevel: "very_high", applicableRate: "종합과세 49.5% → 분리과세 22~33%",
    requirements: [{ id: "r1", description: "법인 주주/대표이사", type: "employment", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제14조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "retained_earnings", label: "이익잉여금", type: "number", unit: "원", required: true },
      { id: "dividend_amount", label: "배당 예정 금액", type: "number", unit: "원", required: true },
      { id: "other_income", label: "기타 종합소득", type: "number", unit: "원", required: true },
    ],
    calculationFormula: "분리과세 세금 vs 종합과세 세금 비교. 고소득일수록 분리과세 유리.",
    urgency: "year_round", difficulty: "hard",
    steps: ["이익잉여금 현황 파악", "배당 금액 시뮬레이션", "종합과세 vs 분리과세 비교", "최적 배당 시점/금액 결정"],
    contentHook: { title: "2026 배당소득 혁명! 사장님 세금 22%p 절약하는 법", hook: "이익잉여금 쌓아두던 사장님들, 지금이 배당 적기!", targetKeyword: "배당소득 분리과세 2026 법인", estimatedViews: "high" },
  },
  {
    id: "corp_loss_carryforward",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "corporate", subcategory: "이월결손금",
    savingType: "deduction", targetAudience: ["corporation"],
    name: "이월결손금 공제",
    shortDescription: "과거 15년 내 결손금을 당기 소득에서 공제",
    fullDescription: "법인의 사업연도 결손금은 향후 15년간 이월하여 소득에서 공제 가능. 중소기업은 100% 공제, 대기업은 60% 한도. 적자 발생 시 법인세 신고를 정확히 해야 향후 활용 가능.",
    tags: ["이월결손금", "결손금", "법인세", "적자"],
    impactLevel: "high", applicableRate: "중소 100% / 대기업 60%",
    requirements: [{ id: "r1", description: "과거 사업연도 결손금 존재", type: "other", critical: true }],
    legalBasis: [{ law: "법인세법", article: "제13조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "loss_amount", label: "이월결손금", type: "number", unit: "원", required: true },
      { id: "current_income", label: "당기 소득", type: "number", unit: "원", required: true },
    ],
    calculationFormula: "공제액 = min(이월결손금, 당기소득 × 100%(중소) 또는 60%(대기업))",
    urgency: "year_round", difficulty: "medium",
    steps: ["과거 15년 내 결손금 확인", "법인세 신고 시 이월결손금 공제 적용"],
  },
  {
    id: "corp_entertainment_expense",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "corporate", subcategory: "접대비",
    savingType: "deduction", targetAudience: ["corporation", "sole_proprietor"],
    name: "접대비 한도 관리",
    shortDescription: "접대비 한도 내 처리로 경비 극대화 (기본 3,600만원)",
    fullDescription: "법인의 접대비는 기본한도 3,600만원(중소기업) + 수입금액에 따른 추가한도로 손금산입 가능. 1만원 초과 접대비는 법인카드/세금계산서 등 적격증빙 필수. 한도 초과분은 손금불산입.",
    tags: ["접대비", "손금", "경비", "적격증빙"],
    impactLevel: "medium", maxDeductionAmount: 36_000_000, applicableRate: "기본 3,600만+수입금액별",
    requirements: [{ id: "r1", description: "법인 또는 사업자", type: "business_type", critical: true }],
    legalBasis: [{ law: "법인세법", article: "제25조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "revenue", label: "연 매출", type: "number", unit: "원", required: true },
      { id: "entertainment", label: "접대비 지출", type: "number", unit: "원", required: true },
    ],
    calculationFormula: "한도 = 3,600만 + 수입금액별 추가한도. 한도 내 금액만 손금 인정.",
    urgency: "year_round", difficulty: "easy",
    steps: ["접대비 한도 계산", "한도 내 지출 관리", "적격증빙 수취 (법인카드 필수)"],
  },
  {
    id: "corp_depreciation",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "corporate", subcategory: "감가상각",
    savingType: "deduction", targetAudience: ["corporation", "sole_proprietor"],
    name: "감가상각 방법 선택 전략",
    shortDescription: "정률법 vs 정액법 선택으로 초기 비용 극대화",
    fullDescription: "유형자산의 감가상각 방법을 정률법(초기 비용↑)과 정액법(균등) 중 선택. 초기 수익이 큰 사업은 정률법으로 초기 법인세 절감. 건물은 정액법만 가능.",
    tags: ["감가상각", "정률법", "정액법", "유형자산"],
    impactLevel: "medium", applicableRate: "방법에 따라 초기 비용 차이",
    requirements: [{ id: "r1", description: "감가상각 대상 유형자산 보유", type: "asset", critical: true }],
    legalBasis: [{ law: "법인세법", article: "제23조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "asset_value", label: "자산 취득가액", type: "number", unit: "원", required: true },
      { id: "useful_life", label: "내용연수", type: "number", unit: "년", required: true },
    ],
    calculationFormula: "정액법: 매년 동일 금액. 정률법: 초기 높고 점점 감소.", urgency: "year_round", difficulty: "medium",
    steps: ["자산별 내용연수 확인", "정률법 vs 정액법 시뮬레이션", "신고 시 감가상각 방법 선택"],
  },
  {
    id: "corp_tax_free_benefit",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "corporate", subcategory: "복리후생",
    savingType: "exemption", targetAudience: ["corporation", "business_owner"],
    name: "비과세 복리후생비 활용",
    shortDescription: "식대 월 20만원, 자가운전보조금 월 20만원 등 비과세",
    fullDescription: "임직원에게 지급하는 식대(월 20만원), 자가운전보조금(월 20만원), 연구보조비(월 20만원), 생산직 야간근무수당 등은 비과세. 법인은 전액 경비처리, 직원은 소득세 면제.",
    tags: ["비과세", "식대", "자가운전", "복리후생", "비과세수당"],
    impactLevel: "medium", applicableRate: "식대·교통비·연구비 각 월 20만원",
    requirements: [{ id: "r1", description: "근로계약서에 비과세 항목 명시", type: "employment", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제12조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "employee_count", label: "직원 수", type: "number", unit: "명", required: true },
    ],
    calculationFormula: "직원당 비과세 합계 = (식대+교통비) × 12 = 480만원/년. 법인 경비+직원 세금 절감",
    urgency: "year_round", difficulty: "easy",
    steps: ["비과세 항목 정리 (식대, 교통비 등)", "급여체계에 비과세 항목 분리", "근로계약서 반영"],
    contentHook: { title: "사장님도 직원도 윈윈! 비과세 수당 총정리", hook: "같은 급여인데 세금 연 50만원 차이?!", targetKeyword: "비과세 수당 종류 2026", estimatedViews: "medium" },
  },
]
