// ============================================================
// 06. 양도소득세 절세 항목
// ============================================================
import type { TaxSavingItem } from "@/types/tax-database"

export const capitalGains: TaxSavingItem[] = [
  {
    id: "cg_1house_exemption",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "capital_gains", subcategory: "1세대1주택",
    savingType: "exemption", targetAudience: ["all"],
    name: "1세대 1주택 비과세",
    shortDescription: "실거래가 12억 이하 1주택 양도 시 비과세",
    fullDescription: "1세대가 1주택을 2년 이상 보유(조정대상지역은 2년 거주 포함) 후 양도 시, 실거래가 12억원 이하분은 양도소득세 비과세. 12억 초과 고가주택은 초과분에만 과세.",
    tags: ["1세대1주택", "비과세", "양도소득세", "2년보유"],
    impactLevel: "very_high", applicableRate: "12억 이하 전액 비과세",
    requirements: [
      { id: "req_1", description: "1세대 1주택", type: "asset", critical: true },
      { id: "req_2", description: "2년 이상 보유", type: "period", value: "2년 이상", critical: true },
      { id: "req_3", description: "조정대상지역: 2년 이상 거주", type: "period", value: "2년 이상 거주", critical: false },
    ],
    legalBasis: [{ law: "소득세법", article: "제89조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "sale_price", label: "양도가액", type: "number", unit: "원", required: true },
      { id: "purchase_price", label: "취득가액", type: "number", unit: "원", required: true },
      { id: "holding_period", label: "보유기간", type: "number", unit: "년", required: true },
    ],
    calculationFormula: "12억 이하: 세금 0원. 12억 초과: (양도차익 × 12억초과분/양도가액) × 세율",
    urgency: "event_based", difficulty: "medium",
    steps: ["1세대 1주택 해당 여부 확인", "보유기간 및 거주기간 확인", "양도가액 12억 초과 여부 확인"],
    contentHook: { title: "내 집 팔 때 세금 0원? 1주택 비과세 완벽 가이드", hook: "12억 이하 주택, 2년만 보유하면 양도세 0원!", targetKeyword: "1세대1주택 비과세 조건 2026", estimatedViews: "high" },
    warnings: [
      "조정대상지역 소재 주택은 2년 보유 + 2년 거주 요건 모두 충족 필수 — 거주 미충족 시 비과세 불인정",
      "취득 당시 조정대상지역 여부 기준으로 거주 요건 적용 — 이후 지역 해제와 무관",
      "비과세 신청은 양도일이 속한 달의 말일부터 2개월 이내 신고 (양도소득세 예정신고)",
      "세대 분리 요건 미충족(자녀 동거 등) 시 1세대로 합산되어 다주택 과세 위험",
    ],
    practicalCases: [
      {
        title: "서울 아파트 2년 보유·거주 후 12억 이하 매도",
        situation: "서울 조정대상지역 아파트를 5억에 취득, 2년 이상 보유·거주 후 10억에 양도 (양도차익 5억)",
        calculation: "양도가액 10억 < 12억 → 전액 비과세. 양도소득세 0원",
        result: "비과세 요건 충족으로 양도세 0원. 일반 과세 적용 시 약 1억 2,000만원 세금 발생",
        taxSaved: 120000000,
      },
      {
        title: "고가주택 18억 양도 시 초과분 과세",
        situation: "12억에 취득한 주택을 18억에 양도 (양도차익 6억, 2년 이상 보유·거주)",
        calculation: "비과세분: 6억 × (12억/18억) = 4억. 과세분: 6억 × (6억/18억) = 2억. 세율 38% 적용 시 약 6,200만원",
        result: "12억 초과분 2억에만 과세. 비과세 없이 6억 전액 과세 시 약 1억 8,600만원 대비 약 1억 2,400만원 절감",
        taxSaved: 124000000,
      },
    ],
  },
  {
    id: "cg_long_term_holding",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "capital_gains", subcategory: "장기보유특별공제",
    savingType: "deduction", targetAudience: ["all", "investor"],
    name: "장기보유특별공제",
    shortDescription: "3년↑ 보유 부동산 양도차익 최대 80% 공제",
    fullDescription: "3년 이상 보유한 부동산 양도 시 보유기간에 따라 양도차익의 최대 30%(일반) 공제. 1세대 1주택(12억 초과)은 보유기간 최대 40% + 거주기간 최대 40% = 합산 80% 공제 가능.",
    tags: ["장기보유특별공제", "양도소득세", "보유기간", "거주기간"],
    impactLevel: "high", applicableRate: "일반 최대 30% / 1주택 최대 80%",
    requirements: [
      { id: "req_1", description: "3년 이상 보유", type: "period", value: "3년 이상", critical: true },
      { id: "req_2", description: "1세대1주택 80% 적용: 2년 이상 거주", type: "period", critical: false },
    ],
    legalBasis: [{ law: "소득세법", article: "제95조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "gain", label: "양도차익", type: "number", unit: "원", required: true },
      { id: "holding_years", label: "보유기간", type: "number", unit: "년", required: true },
      { id: "living_years", label: "거주기간 (1주택 시)", type: "number", unit: "년", required: false },
      { id: "is_single_home", label: "1세대1주택 여부", type: "boolean", required: true },
    ],
    calculationFormula: "일반: 연 2%씩 최대 30%. 1주택: 보유 연4%×10년(40%) + 거주 연4%×10년(40%) = 80%",
    urgency: "event_based", difficulty: "medium",
    steps: ["보유기간·거주기간 정확히 계산", "1세대1주택 해당 여부 확인", "양도소득세 신고 시 공제 적용"],
    warnings: [
      "비사업용 토지는 장기보유특별공제 적용 불가 + 중과세율(기본세율 +10%p) 적용",
      "다주택자(2주택 이상)의 조정대상지역 주택은 중과 적용 시 장기보유특별공제 배제 (유예기간 확인 필수)",
      "1세대1주택 80% 공제는 보유기간과 거주기간 각각 연 4%씩 누적 — 거주기간이 짧으면 공제율 대폭 감소",
      "취득가액 증빙 없을 경우 환산취득가액 적용 → 양도차익 과다 계산 위험",
    ],
    practicalCases: [
      {
        title: "10년 보유·거주 1주택자 80% 장기보유특별공제 적용",
        situation: "1세대1주택자가 15억 주택(취득가 5억)을 10년 이상 보유·거주 후 양도. 양도차익 10억, 12억 초과분 과세분 약 4억",
        calculation: "장기보유특별공제 80% 적용 시 공제액 3.2억. 과세표준 0.8억. 세율 35% 구간 → 세액 약 1,760만원",
        result: "공제 미적용 시 세액 약 1억 4,800만원 대비 약 1억 3,040만원 절세 효과",
        taxSaved: 130400000,
      },
      {
        title: "일반 토지 5년 보유 후 양도, 공제 10%",
        situation: "5년 보유한 상업용 토지(양도차익 2억) 양도. 비사업용 토지 아닌 경우",
        calculation: "장기보유특별공제 10%(5년 × 2%) 적용. 공제액 2,000만원. 과세표준 1억 8,000만원. 세율 38% → 세액 약 4,560만원",
        result: "공제 미적용 시 세액 약 5,360만원 대비 800만원 절세",
        taxSaved: 8000000,
      },
    ],
  },
  {
    id: "cg_multi_home_deferral",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "capital_gains", subcategory: "다주택 전략",
    savingType: "deferral", targetAudience: ["multi_home_owner", "investor"],
    name: "다주택자 중과 유예 활용 (2026.5.9까지)",
    shortDescription: "조정대상지역 다주택 중과세율 한시 유예 활용",
    fullDescription: "2022.5.10~2026.5.9 양도분에 대해 조정대상지역 다주택자 양도세 중과(+20~30%p) 적용 배제 및 장기보유특별공제 적용. 유예 기간 내 매도 전략 필요.",
    tags: ["다주택자", "양도세", "중과유예", "조정대상지역"],
    impactLevel: "very_high", applicableRate: "중과세율(+20~30%p) 배제",
    requirements: [
      { id: "req_1", description: "2026년 5월 9일까지 양도", type: "period", value: "~2026.5.9", critical: true },
    ],
    legalBasis: [{ law: "소득세법 시행령", article: "부칙", effectiveDate: "2022-05-10", expiryDate: "2026-05-09" }],
    calculationParams: [
      { id: "gain", label: "양도차익", type: "number", unit: "원", required: true },
      { id: "home_count", label: "보유 주택 수", type: "number", unit: "채", required: true },
    ],
    calculationFormula: "중과 시: 기본세율 + 20~30%p. 유예 시: 기본세율만 적용. 차이가 절세액.",
    urgency: "year_end", difficulty: "hard",
    steps: ["보유 주택 현황 정리", "유예 기간 내 매도 계획 수립", "중과 vs 일반 세액 비교 시뮬레이션", "2026.5.9 전 양도 완료"],
    contentHook: { title: "다주택자 마지막 기회! 2026년 5월까지 팔아야 하는 이유", hook: "5월 넘기면 양도세 20%p 추가, 수억 차이!", targetKeyword: "다주택자 양도세 중과 유예 2026", estimatedViews: "high" },
    warnings: [
      "2026.5.10 이후 중과 부활 가능성 — 정부 정책 주시 필요",
      "잔금 청산일 기준으로 양도일 판단 — 계약일이 아닌 잔금일이 5월 9일 이전이어야 유예 적용",
      "유예 기간 내라도 장기보유특별공제 적용은 조정대상지역 내 주택 여부에 따라 달라짐",
      "취득가액 증빙 불충분 시 환산취득가액 적용되어 양도차익이 커질 수 있음 — 계약서·등기부 철저 보관",
    ],
    practicalCases: [
      {
        title: "조정대상지역 2주택자 유예 기간 내 1주택 매도",
        situation: "서울 아파트 2채 보유 중 1채(취득가 4억, 양도가 9억)를 2026년 4월 양도. 양도차익 5억",
        calculation: "유예 적용: 기본세율(40%) + 장기보유특별공제(10년 20%) 적용. 과세표준 4억 → 세액 약 1억 3,200만원 / 중과 적용(+20%p): 과세표준 5억 × 60% → 세액 약 2억 7,000만원",
        result: "유예 기간 활용으로 약 1억 3,800만원 세금 절감",
        taxSaved: 138000000,
      },
      {
        title: "3주택자 유예 기간 내 비조정 1주택 선매도",
        situation: "3주택 보유(조정 2채, 비조정 1채) 중 비조정 1채(양도차익 2억)를 5월 전 매도",
        calculation: "비조정 3주택 중과(+30%p) vs 유예(기본세율 40%): 유예 시 세액 약 6,400만원, 중과 시 약 1억 1,200만원",
        result: "유예 기간 내 매도로 약 4,800만원 절세",
        taxSaved: 48000000,
      },
    ],
  },
]
