// ============================================================
// 06-extra. 양도소득세 + 부동산 절세 추가 항목
// ============================================================
import type { TaxSavingItem } from "@/types/tax-database"

export const capitalGainsExtra: TaxSavingItem[] = [
  {
    id: "cg_temporary_2house",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "capital_gains", subcategory: "일시적 2주택",
    savingType: "exemption", targetAudience: ["all"],
    name: "일시적 2주택 비과세 특례",
    shortDescription: "이사 등으로 일시적 2주택 시 3년 내 기존 주택 양도 시 비과세",
    fullDescription: "1주택 보유 중 새 주택을 취득하여 일시적 2주택이 된 경우, 새 주택 취득일로부터 3년 이내에 기존 주택을 양도하면 1세대 1주택 비과세 적용.",
    tags: ["일시적2주택", "비과세", "이사", "양도세"],
    impactLevel: "very_high", applicableRate: "12억 이하 전액 비과세",
    requirements: [
      { id: "r1", description: "새 주택 취득 전 1주택 보유", type: "asset", critical: true },
      { id: "r2", description: "새 주택 취득 후 3년 내 기존 주택 양도", type: "period", value: "3년 이내", critical: true },
    ],
    legalBasis: [{ law: "소득세법 시행령", article: "제155조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "old_house_value", label: "기존 주택 양도가액", type: "number", unit: "원", required: true },
      { id: "new_house_date", label: "새 주택 취득일", type: "date", required: true },
    ],
    calculationFormula: "3년 내 기존 주택 양도 → 1세대1주택 비과세 적용", urgency: "event_based", difficulty: "medium",
    steps: ["일시적 2주택 해당 여부 확인", "3년 기한 계산", "기한 내 기존 주택 매도 계획"],
    contentHook: { title: "이사할 때 양도세 0원! 일시적 2주택 비과세 조건", hook: "새 집 사고 3년 안에 옛 집 팔면 세금 0원!", targetKeyword: "일시적 2주택 비과세 3년", estimatedViews: "high" },
    warnings: [
      "3년 기한 내 미양도 시 비과세 불인정 — 기한 경과 후 양도 시 다주택자로 중과 위험",
      "1세대 1주택 비과세 요건(2년 보유·조정대상지역 2년 거주)은 기존 주택 기준으로 별도 충족 필요",
      "새 주택 취득일 기준으로 3년 기산 — 계약일이 아닌 잔금일(등기일) 기준 확인 필수",
      "상속·증여로 취득한 주택이 포함된 경우 일시적 2주택 특례 적용 여부 별도 검토 필요",
    ],
    practicalCases: [
      {
        title: "이사로 일시적 2주택, 3년 내 기존 주택 매도 비과세",
        situation: "서울 기존 주택(취득가 5억, 2년 이상 보유·거주) 보유 중 새 주택 취득. 2년 후 기존 주택을 9억에 양도 (양도차익 4억)",
        calculation: "새 주택 취득 후 2년 이내 양도 → 일시적 2주택 비과세 요건 충족. 양도가액 9억 < 12억 → 전액 비과세",
        result: "비과세 요건 충족으로 양도세 0원. 중과 적용 시 약 9,600만원 세금 발생 예상",
        taxSaved: 96000000,
      },
      {
        title: "기한 초과로 비과세 실패 — 주의 사례",
        situation: "새 주택 취득 후 3년 1개월이 지나 기존 주택 양도 (양도차익 3억)",
        calculation: "3년 초과로 일시적 2주택 특례 미적용. 2주택 일반과세 기본세율(38%) 적용 → 세액 약 8,400만원",
        result: "기한을 한 달 초과했을 뿐이지만 비과세 혜택 상실. 기한 관리가 핵심",
        taxSaved: 0,
      },
    ],
  },
  {
    id: "cg_relocation_exemption",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "capital_gains", subcategory: "비과세특례",
    savingType: "exemption", targetAudience: ["employee"],
    name: "직장이전 비과세 (부득이한 사유)",
    shortDescription: "전근, 취학 등 부득이한 사유로 세대원 이동 시 비과세",
    fullDescription: "직장의 변경, 전근, 취학, 1년 이상 질병치료 등 부득이한 사유로 세대원 전원이 다른 시군으로 이전하는 경우, 거주기간 요건 없이 2년 보유만으로 비과세 적용.",
    tags: ["전근", "직장이전", "비과세", "부득이한사유"],
    impactLevel: "high", applicableRate: "비과세",
    requirements: [
      { id: "r1", description: "직장변경/전근/취학 등 부득이한 사유", type: "other", critical: true },
      { id: "r2", description: "다른 시·군으로 이전", type: "region", critical: true },
      { id: "r3", description: "2년 이상 보유", type: "period", value: "2년 이상", critical: true },
    ],
    legalBasis: [{ law: "소득세법 시행령", article: "제154조", effectiveDate: "2026-01-01" }],
    calculationParams: [], calculationFormula: "부득이한 사유 해당 시 거주 요건 면제, 2년 보유만 충족하면 비과세",
    urgency: "event_based", difficulty: "medium",
    steps: ["부득이한 사유 해당 여부 확인", "재직증명서/전근발령서 등 증빙 준비", "양도소득세 신고 시 비과세 적용"],
    warnings: [
      "부득이한 사유 증빙 서류(발령서·재직증명서·진단서 등) 미보관 시 비과세 거부 위험",
      "세대원 전원이 이전해야 적용 — 일부 세대원만 이동 시 비과세 불인정",
      "다른 시·군 이전 요건: 같은 시·군 내 이동은 해당 없음 (서울 → 서울 내 구 이동 불인정)",
      "비과세 신청 기한(양도 후 2개월 이내) 준수 필수 — 기한 경과 시 가산세 발생",
    ],
    practicalCases: [
      {
        title: "전근 발령으로 타 지역 이사, 거주 1년 주택 비과세",
        situation: "서울 아파트(취득가 6억, 2년 보유·거주 1년) 보유 중 부산 전근 발령. 세대 전원 이전 후 서울 아파트를 10억에 양도 (양도차익 4억)",
        calculation: "부득이한 사유(전근)로 거주요건 면제. 2년 보유 충족 → 비과세. 양도가액 10억 < 12억 → 전액 비과세",
        result: "일반 과세 시 세액 약 9,600만원. 비과세 적용으로 전액 절세",
        taxSaved: 96000000,
      },
      {
        title: "1년 이상 질병 치료로 타 지역 이전 후 주택 매도",
        situation: "경기도 주택(취득가 3억, 2년 보유) 보유 중 서울 병원 1년 이상 입원치료로 세대 전원 서울 이전. 주택을 5억에 양도 (양도차익 2억)",
        calculation: "부득이한 사유(질병) 해당 시 거주요건 면제. 2년 보유 충족 → 5억 < 12억 → 비과세",
        result: "비과세 요건 충족 시 세금 0원. 증빙 미비로 과세 시 약 3,800만원 세금 발생",
        taxSaved: 38000000,
      },
    ],
  },
  {
    id: "cg_overseas_stock_switch",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "capital_gains", subcategory: "해외주식",
    savingType: "reduction", targetAudience: ["investor"],
    name: "해외주식 → 국내주식 갈아타기 세금 감면 (2026 한시)",
    shortDescription: "해외주식 매도 → 국내주식 장기투자 시 양도세 최대 100% 감면",
    fullDescription: "2025.12.23까지 보유한 해외주식을 매도하여 원화 환전 후 국내 주식에 장기투자 시, 2026년 한 해 양도소득세 22% 감면. 특히 2026년 1분기 갈아타기 시 100% 전액 감면.",
    tags: ["해외주식", "국내주식", "갈아타기", "양도세감면", "한시"],
    impactLevel: "high", applicableRate: "1분기 100% / 2~4분기 점차 감소",
    requirements: [
      { id: "r1", description: "2025.12.23까지 보유한 해외주식", type: "period", critical: true },
      { id: "r2", description: "2026년 내 국내주식 장기투자", type: "period", value: "2026년", critical: true },
    ],
    legalBasis: [{ law: "조세특례제한법", article: "한시 특례", effectiveDate: "2026-01-01", expiryDate: "2026-12-31" }],
    calculationParams: [
      { id: "overseas_gain", label: "해외주식 양도차익", type: "number", unit: "원", required: true },
      { id: "switch_quarter", label: "갈아타기 시기", type: "select", options: [
        { label: "1분기 (1~3월)", value: "q1" },
        { label: "2분기 (4~6월)", value: "q2" },
        { label: "3분기 (7~9월)", value: "q3" },
        { label: "4분기 (10~12월)", value: "q4" },
      ], required: true },
    ],
    calculationFormula: "1분기: 양도세 100% 면제. 이후 점차 감소.", urgency: "year_end", difficulty: "medium",
    steps: ["해외주식 보유 현황 확인", "양도차익 추정", "1분기 내 매도/환전/국내투자 실행"],
    contentHook: { title: "해외주식 팔고 국내주식 사면 세금 0원?! 2026 한시 특례", hook: "3월까지 갈아타면 양도세 100% 면제!", targetKeyword: "해외주식 국내주식 갈아타기 세금 2026", estimatedViews: "high" },
    warnings: [
      "2025.12.23 이후 취득한 해외주식은 특례 대상 제외 — 보유 시점 정확히 확인 필수",
      "국내주식 장기투자 요건 미충족(단기 재매도 등) 시 감면 취소 및 가산세 위험",
      "환전 과정에서 발생하는 환차손익은 별도 세무 처리 필요",
      "2026년 2분기 이후 갈아타기는 감면율이 줄어드므로 분기별 감면율 최신 시행령 확인 필수",
    ],
    practicalCases: [
      {
        title: "1분기 갈아타기로 해외주식 양도세 100% 면제",
        situation: "2024년 취득한 미국 주식 포트폴리오 양도차익 5,000만원. 2026년 1분기(3월 이전) 전량 매도 후 국내 우량주 장기투자",
        calculation: "해외주식 양도세(22%) = 1,100만원. 1분기 갈아타기 → 100% 감면 → 세액 0원",
        result: "1분기 내 실행으로 1,100만원 전액 절세. 4분기 실행 시 감면율 축소로 절세 효과 감소",
        taxSaved: 11000000,
      },
      {
        title: "분기별 감면율 차이 비교",
        situation: "해외주식 양도차익 1억원 보유자가 갈아타기 시기를 고민 중",
        calculation: "1분기: 100% 감면 → 세액 0원 / 2분기: 감면율 축소(가정 75%) → 세액 약 550만원 / 4분기: 감면율 25% → 세액 약 1,650만원",
        result: "갈아타기 시기가 이를수록 절세 효과 극대화. 1분기와 4분기 차이 최대 2,200만원",
        taxSaved: 22000000,
      },
    ],
  },
  {
    id: "cg_installment_payment",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "capital_gains", subcategory: "납부전략",
    savingType: "deferral", targetAudience: ["all", "investor"],
    name: "양도소득세 분납/물납",
    shortDescription: "양도세 1천만원 초과 시 2개월 분납, 부동산 물납 가능",
    fullDescription: "양도소득세가 1천만원을 초과하는 경우 납부기한 경과 후 2개월 이내 분납 가능. 세액의 50% 이하를 분납할 수 있어 자금 부담을 완화.",
    tags: ["분납", "양도소득세", "납부전략"],
    impactLevel: "low", applicableRate: "세액 50% 이하 분납",
    requirements: [{ id: "r1", description: "양도세 1천만원 초과", type: "income_limit", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제112조", effectiveDate: "2026-01-01" }],
    calculationParams: [{ id: "tax_amount", label: "양도소득세", type: "number", unit: "원", required: true }],
    calculationFormula: "1천만원 초과분의 50% 이하를 2개월 분납", urgency: "event_based", difficulty: "easy",
    steps: ["양도세 확정 후 분납 가능 여부 확인", "신고 시 분납 신청"],
    warnings: [
      "분납 신청은 예정신고·확정신고 시에만 가능 — 신고 기한 경과 후 분납 신청 불가",
      "분납 기한(납부기한 후 2개월) 내 미납 시 가산세(납부지연 0.022%/일) 부과",
      "분납은 이자 없이 납부 기간 연장 혜택이나 세금 자체를 줄여주지는 않음 — 절세가 아닌 자금 흐름 관리 수단",
      "물납은 현금 납부가 곤란한 경우에만 허용 — 국세청 승인 절차 필요",
    ],
    practicalCases: [
      {
        title: "양도세 5,000만원, 분납으로 자금 부담 완화",
        situation: "양도소득세 5,000만원 확정. 일시 납부 시 자금 부담 — 분납 신청",
        calculation: "1차 납부(신고기한 내): 2,500만원. 2차 납부(2개월 후): 2,500만원. 분납 가능 한도(50%) = 2,500만원",
        result: "2개월 여유 확보로 단기 자금 운용 가능. 총 납부세액 동일하나 현금흐름 개선",
        taxSaved: 0,
      },
      {
        title: "1억 양도세 발생 시 분납 최대 활용",
        situation: "양도소득세 1억원 확정. 분납 한도 50% 신청",
        calculation: "1차: 5,000만원 신고기한 내 납부. 2차: 5,000만원 2개월 이내 납부",
        result: "5,000만원에 대한 2개월 자금 운용 여유 확보. 예금 이자(연 3% 기준 약 25만원) 수준의 간접 이익",
        taxSaved: 0,
      },
    ],
  },
]
