// ============================================================
// 06-extra. 양도소득세 + 부동산 절세 추가 항목
// ============================================================
import type { TaxSavingItem } from "@/types/tax-database"

export const capitalGainsExtra: TaxSavingItem[] = [
  {
    id: "cg_temporary_2house",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "capital_gains", subcategory: "일시적 2주택",
    savingType: "exemption", targetAudience: ["all"],
    name: "일시적 2주택 비과세 특례",
    shortDescription: "이사 등으로 일시적 2주택 시 3년 내 기존 주택 양도 시 비과세",
    fullDescription: "1주택 보유 중 새 주택을 취득하여 일시적 2주택이 된 경우, 새 주택 취득일로부터 3년 이내에 기존 주택을 양도하면 1세대 1주택 비과세 적용.",
    tags: ["일시적2주택", "비과세", "이사", "양도세"],
    impactLevel: "very_high", applicableRate: "12억 이하 전액 비과세",
    requirements: [
      { id: "r1", description: "새 주택 취득 전 1주택 보유", type: "asset", critical: true },
      { id: "r2", description: "새 주택 취득 후 3년 내 기존 주택 양도", type: "period", value: "3년 이내", critical: true },
    ],
    legalBasis: [{ law: "소득세법 시행령", article: "제155조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "old_house_value", label: "기존 주택 양도가액", type: "number", unit: "원", required: true },
      { id: "new_house_date", label: "새 주택 취득일", type: "date", required: true },
    ],
    calculationFormula: "3년 내 기존 주택 양도 → 1세대1주택 비과세 적용", urgency: "event_based", difficulty: "medium",
    steps: ["일시적 2주택 해당 여부 확인", "3년 기한 계산", "기한 내 기존 주택 매도 계획"],
    contentHook: { title: "이사할 때 양도세 0원! 일시적 2주택 비과세 조건", hook: "새 집 사고 3년 안에 옛 집 팔면 세금 0원!", targetKeyword: "일시적 2주택 비과세 3년", estimatedViews: "high" },
  },
  {
    id: "cg_relocation_exemption",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "capital_gains", subcategory: "비과세특례",
    savingType: "exemption", targetAudience: ["employee"],
    name: "직장이전 비과세 (부득이한 사유)",
    shortDescription: "전근, 취학 등 부득이한 사유로 세대원 이동 시 비과세",
    fullDescription: "직장의 변경, 전근, 취학, 1년 이상 질병치료 등 부득이한 사유로 세대원 전원이 다른 시군으로 이전하는 경우, 거주기간 요건 없이 2년 보유만으로 비과세 적용.",
    tags: ["전근", "직장이전", "비과세", "부득이한사유"],
    impactLevel: "high", applicableRate: "비과세",
    requirements: [
      { id: "r1", description: "직장변경/전근/취학 등 부득이한 사유", type: "other", critical: true },
      { id: "r2", description: "다른 시·군으로 이전", type: "region", critical: true },
      { id: "r3", description: "2년 이상 보유", type: "period", value: "2년 이상", critical: true },
    ],
    legalBasis: [{ law: "소득세법 시행령", article: "제154조", effectiveDate: "2026-01-01" }],
    calculationParams: [], calculationFormula: "부득이한 사유 해당 시 거주 요건 면제, 2년 보유만 충족하면 비과세",
    urgency: "event_based", difficulty: "medium",
    steps: ["부득이한 사유 해당 여부 확인", "재직증명서/전근발령서 등 증빙 준비", "양도소득세 신고 시 비과세 적용"],
  },
  {
    id: "cg_overseas_stock_switch",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "capital_gains", subcategory: "해외주식",
    savingType: "reduction", targetAudience: ["investor"],
    name: "해외주식 → 국내주식 갈아타기 세금 감면 (2026 한시)",
    shortDescription: "해외주식 매도 → 국내주식 장기투자 시 양도세 최대 100% 감면",
    fullDescription: "2025.12.23까지 보유한 해외주식을 매도하여 원화 환전 후 국내 주식에 장기투자 시, 2026년 한 해 양도소득세 22% 감면. 특히 2026년 1분기 갈아타기 시 100% 전액 감면.",
    tags: ["해외주식", "국내주식", "갈아타기", "양도세감면", "한시"],
    impactLevel: "high", applicableRate: "1분기 100% / 2~4분기 점차 감소",
    requirements: [
      { id: "r1", description: "2025.12.23까지 보유한 해외주식", type: "period", critical: true },
      { id: "r2", description: "2026년 내 국내주식 장기투자", type: "period", value: "2026년", critical: true },
    ],
    legalBasis: [{ law: "조세특례제한법", article: "한시 특례", effectiveDate: "2026-01-01", expiryDate: "2026-12-31" }],
    calculationParams: [
      { id: "overseas_gain", label: "해외주식 양도차익", type: "number", unit: "원", required: true },
      { id: "switch_quarter", label: "갈아타기 시기", type: "select", options: [
        { label: "1분기 (1~3월)", value: "q1" },
        { label: "2분기 (4~6월)", value: "q2" },
        { label: "3분기 (7~9월)", value: "q3" },
        { label: "4분기 (10~12월)", value: "q4" },
      ], required: true },
    ],
    calculationFormula: "1분기: 양도세 100% 면제. 이후 점차 감소.", urgency: "year_end", difficulty: "medium",
    steps: ["해외주식 보유 현황 확인", "양도차익 추정", "1분기 내 매도/환전/국내투자 실행"],
    contentHook: { title: "해외주식 팔고 국내주식 사면 세금 0원?! 2026 한시 특례", hook: "3월까지 갈아타면 양도세 100% 면제!", targetKeyword: "해외주식 국내주식 갈아타기 세금 2026", estimatedViews: "high" },
  },
  {
    id: "cg_installment_payment",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "capital_gains", subcategory: "납부전략",
    savingType: "deferral", targetAudience: ["all", "investor"],
    name: "양도소득세 분납/물납",
    shortDescription: "양도세 1천만원 초과 시 2개월 분납, 부동산 물납 가능",
    fullDescription: "양도소득세가 1천만원을 초과하는 경우 납부기한 경과 후 2개월 이내 분납 가능. 세액의 50% 이하를 분납할 수 있어 자금 부담을 완화.",
    tags: ["분납", "양도소득세", "납부전략"],
    impactLevel: "low", applicableRate: "세액 50% 이하 분납",
    requirements: [{ id: "r1", description: "양도세 1천만원 초과", type: "income_limit", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제112조", effectiveDate: "2026-01-01" }],
    calculationParams: [{ id: "tax_amount", label: "양도소득세", type: "number", unit: "원", required: true }],
    calculationFormula: "1천만원 초과분의 50% 이하를 2개월 분납", urgency: "event_based", difficulty: "easy",
    steps: ["양도세 확정 후 분납 가능 여부 확인", "신고 시 분납 신청"],
  },
]
