// ============================================================
// 08. 상속세·증여세 절세 항목 (가업승계 포함)
// ============================================================

import type { TaxSavingItem } from "@/types/tax-database"

export const inheritanceGift: TaxSavingItem[] = [
  // ── 가업상속공제 ──────────────────────────────────────────
  {
    id: "inheritance_business_deduction",
    version: "2026.1",
    lastUpdated: "2026-01-01",
    category: "inheritance",
    subcategory: "가업승계",
    savingType: "deduction",
    targetAudience: ["heir", "business_owner"],
    name: "가업상속공제",
    shortDescription: "10년↑ 경영 중소·중견기업 최대 600억 상속공제",
    fullDescription: "피상속인이 10년 이상 경영한 중소기업 또는 매출 5,000억 미만 중견기업을 상속인에게 승계할 때, 가업 영위 기간에 따라 최대 600억원까지 상속재산에서 공제합니다. 사후관리 5년간 업종·지분·고용·자산 유지 필수.",
    tags: ["가업승계", "상속공제", "중소기업", "중견기업", "사후관리"],
    impactLevel: "very_high",
    maxDeductionAmount: 60_000_000_000, // 600억
    applicableRate: "10년 300억 / 20년 400억 / 30년 600억",
    requirements: [
      { id: "req_1", description: "피상속인 10년 이상 계속 경영", type: "period", value: "10년 이상", critical: true },
      { id: "req_2", description: "중소기업 또는 매출 5천억 미만 중견기업", type: "business_type", value: "중소기업 또는 중견기업(매출 5천억 미만)", critical: true },
      { id: "req_3", description: "상속인 2년 이상 가업 종사", type: "period", value: "상속개시 전 2년 이상", critical: true },
      { id: "req_4", description: "피상속인 대표이사 재직", type: "employment", critical: true },
      { id: "req_5", description: "상속인 상속세 신고기한 내 임원 취임, 상속개시 후 2년 내 대표이사 취임", type: "employment", critical: true },
    ],
    exclusions: [
      "상속개시일 속하는 사업연도 직전 3년 평균 매출 5천억 이상 중견기업",
      "탈세·회계부정으로 형사처벌받은 경우",
    ],
    conflicts: ["gift_business_succession_special"], // 증여세 과세특례와 일부 중복 제한
    legalBasis: [
      { law: "상속세 및 증여세법", article: "제18조의2", url: "https://www.law.go.kr", effectiveDate: "2026-01-01" },
    ],
    postManagement: {
      period: 5,
      requirements: [
        { item: "업종 유지", standard: "표준산업분류 중분류 내 동일 업종, 1년 이상 휴·폐업 금지", penalty: "공제 전액 추징" },
        { item: "지분 유지", standard: "상속받은 지분 유지", penalty: "처분 비율만큼 추징" },
        { item: "고용 유지", standard: "5년 통산 정규직 수·총급여액 90% 이상 유지", penalty: "미달 비율만큼 추징" },
        { item: "자산 유지", standard: "가업용 자산 40% 이상 처분 금지", penalty: "처분 비율만큼 추징" },
        { item: "대표이사 유지", standard: "상속인이 대표이사 유지", penalty: "공제 전액 추징" },
      ],
    },
    calculationParams: [
      { id: "business_years", label: "피상속인 경영 기간", type: "number", unit: "년", min: 10, required: true },
      { id: "business_value", label: "가업 자산 가치", type: "number", unit: "원", required: true },
      { id: "company_type", label: "기업 유형", type: "select", options: [
        { label: "중소기업", value: "sme" },
        { label: "중견기업 (매출 5천억 미만)", value: "mid" },
      ], required: true },
    ],
    calculationFormula: "공제한도: 10년↑ 300억, 20년↑ 400억, 30년↑ 600억. 공제액 = min(가업자산가치, 한도)",
    schedule: { name: "상속세 신고", deadline: "상속개시일로부터 6개월", singoType: "상속세 신고", singoMethod: "홈택스 또는 세무서 방문" },
    urgency: "event_based",
    difficulty: "expert",
    steps: [
      "가업 영위 기간 확인 (사업자등록증 기준)",
      "피상속인 대표이사 재직 기간 확인",
      "상속인 가업 종사 기간 확인 (2년 이상)",
      "가업 자산 가치 평가 (감정평가)",
      "상속세 신고 시 가업상속공제 신청",
      "사후관리 5년 계획 수립",
    ],
    requiredDocuments: [
      "사업자등록증 사본", "법인등기부등본", "주주명부",
      "재무제표 (최근 10년)", "근로자 명부", "감정평가서",
      "상속인 재직증명서", "가업상속공제 신청서",
    ],
    contentHook: {
      title: "가업승계, 세금 600억 아끼는 법 (2026 최신)",
      hook: "30년 경영한 회사, 상속세 0원 가능합니다!",
      targetKeyword: "가업상속공제 2026",
      estimatedViews: "high",
    },
    warnings: [
      "사후관리 5년 중 요건 위반 시 공제 전액 추징 가능",
      "상속인이 대표이사직을 사임하면 즉시 추징",
      "부동산 임대업은 가업에 해당하지 않을 수 있음",
    ],
    commonMistakes: [
      "상속인의 가업 종사 기간(2년)을 미리 준비하지 않음",
      "사후관리 기간 중 업종 변경하여 추징당함",
      "가업용 자산과 비가업용 자산 구분을 잘못함",
      "구법(7년) 기준으로 사후관리 계획을 수립함 — 현행 5년 기준 적용 필요",
    ],
    relatedItems: ["gift_business_succession_special", "gift_startup_fund"],

    // ── 세무사 수준 정확성 데이터 (2026.4 딥리서치 검증) ──
    verification: {
      status: "self_checked",
      verifiedBy: "시스템 (국세청+법제처+KPMG+삼일PwC+헬프미 교차 검증)",
      verifiedDate: "2026-04-04",
      notes: "상증법 제18조의2, 시행령 제15조~15조의2 확인. 사후관리 5년(2023.1.1 시행) 반영. 연부연납 20년 특례 확인.",
      nextReviewDate: "2026-07-01",
    },
    legalTexts: [
      {
        lawName: "상속세 및 증여세법",
        articleNumber: "제18조의2",
        articleTitle: "가업상속공제",
        fullText: "① 거주자의 사망으로 상속이 개시되는 경우로서 다음 각 호의 요건을 모두 갖춘 경우에는 가업상속 재산가액에 상당하는 금액을 상속세 과세가액에서 공제한다. 다만, 그 공제할 금액은 가업영위기간에 따라 다음 각 호의 구분에 따른 금액을 한도로 한다.",
        keyProvisions: [
          "【가업 요건】 피상속인 10년 이상 계속 경영한 중소기업 또는 매출 5천억 미만 중견기업 (제1항)",
          "【피상속인 요건】 최대주주 등 지분 40% 이상(상장 20%) 10년 이상 보유 + 경영기간 50% 이상 대표이사 재직 (시행령 제15조)",
          "【상속인 요건】 18세 이상, 상속개시 2년 전부터 가업 종사, 신고기한 내 임원 취임, 2년 내 대표이사 취임 (제2항)",
          "【공제한도】 10년↑ 300억, 20년↑ 400억, 30년↑ 600억 (제1항 단서)",
          "【사후관리 5년】 2023.1.1 시행, 구법 7년 (제7항)",
          "【고용유지】 5년 통산 정규직수·총급여 90% 이상 유지 (시행령 제15조의2)",
          "【자산유지】 가업용 자산 40% 이상 처분 금지, 구법 20% (시행령 제15조의2)",
          "【업종유지】 중분류 내 업종 변경 허용, 1년 이상 휴·폐업 금지 (시행령 제15조의2)",
          "【대표이사】 상속인 대표이사 유지 의무 (위반 시 전액 추징)",
          "【연부연납 특례】 가업상속재산 상속세 최장 20년 분할납부 (거치 5년 + 분할 15년), 상증법 제71조",
          "【납부유예】 양도·상속·증여 시점까지 납부유예 가능, 재차 가업승계 시 계속 유예",
          "【대상 업종】 제조업, 건설업, 도소매업, 정보통신업, 물류산업 등 — 부동산 임대업 제외 (시행령 별표)",
        ],
        effectiveDate: "2026-01-01",
        lastAmendedDate: "2023-01-01",
        sourceUrl: "https://www.law.go.kr/법령/상속세및증여세법/제18조의2",
      },
    ],
    practicalCases: [
      {
        title: "30년 중소기업 가업상속 — 상속세 0원",
        situation: "부친이 30년간 운영한 중소제조업체(가업자산 500억)를 장남(가업 5년 종사)이 상속",
        calculation: "가업상속공제 한도 600억 → 500억 전액 공제. 공제 전 상속세 약 200억 → 공제 후 0원 (가업자산분)",
        result: "가업 자산 500억에 대한 상속세 약 200억 절세",
        taxSaved: 20_000_000_000,
        source: "국세청 가업승계 지원제도 안내 (2024)",
      },
      {
        title: "15년 중견기업 가업상속 — 연부연납 활용",
        situation: "매출 2,000억 중견기업(가업자산 350억)을 차남이 상속. 공제 300억, 과세분 50억",
        calculation: "과세표준 50억 × 상속세율 → 약 15억 상속세. 연부연납 20년(거치5+분할15) 적용 → 연 1억씩 분할납부",
        result: "일시 납부 부담 없이 20년간 분할, 사업 운영자금 확보",
        taxSaved: 0,
        source: "헬프미 2026 가업승계 총정리",
      },
      {
        title: "자녀 2명+배우자 상속 — 가업상속공제 + 일괄공제 활용",
        situation: "총 상속재산 20억(가업자산 10억+비가업 10억), 배우자+자녀 2명",
        calculation: "가업상속공제 10억 + 일괄공제 5억 + 배우자공제 5억 = 20억 → 과세표준 0원",
        result: "상속세 0원 (가업상속공제 + 일괄공제 활용, 자녀공제는 현행 5천만원/인)",
        taxSaved: 400_000_000,
        source: "2026_세법변경_핵심요약.md §3",
      },
    ],
    faqs: [
      { question: "사후관리 기간이 7년인가요 5년인가요?", answer: "2023.1.1 이후 상속개시분부터 5년입니다. 구법(2022.12.31 이전 상속개시)은 7년이므로 주의하세요.", legalBasis: "상증법 제18조의2 제7항 (2023.1.1 시행)" },
      { question: "부동산 임대업도 가업에 해당하나요?", answer: "부동산 임대업은 원칙적으로 가업에 해당하지 않습니다. 시행령 별표에서 정하는 업종(제조업, 건설업, 도소매업, 정보통신업 등)에 해당해야 합니다.", legalBasis: "상증법 시행령 제15조 별표" },
      { question: "고용유지 요건은 매년 충족해야 하나요?", answer: "아닙니다. 5년 통산 기준입니다. 정규직 수와 총급여액을 5년 평균으로 90% 이상 유지하면 됩니다 (구법: 매년 80%).", legalBasis: "상증법 시행령 제15조의2" },
      { question: "업종을 변경하면 추징당하나요?", answer: "중분류 내 변경은 허용됩니다. 예: (제조업)음료 → (제조업)자동차부품 = OK. 단, (도매업)의류 → (제조업)의류 = 대분류가 다르므로 추징.", legalBasis: "상증법 시행령 제15조의2 제6항" },
      { question: "연부연납 20년은 어떻게 신청하나요?", answer: "상속세 신고 시 연부연납 신청서를 제출합니다. 거치기간 5년 후 15년간 분할 납부. 일반상속세는 최장 5~10년이지만, 가업상속은 20년 특례.", legalBasis: "상증법 제71조" },
      { question: "개인사업자도 가업상속공제 받을 수 있나요?", answer: "네, 가업상속공제는 개인사업자도 가능합니다. 단, 가업승계 증여세 과세특례(제30조의6)는 법인 주식만 대상이므로 개인사업자는 불가합니다.", legalBasis: "상증법 제18조의2 vs 조특법 제30조의6" },
      { question: "납부유예란 뭔가요?", answer: "가업재산 상속·증여 후 양도·상속·증여 시점까지 세금 납부를 유예합니다. 재차 가업승계(자녀→손자) 시 계속 유예 가능.", legalBasis: "상증법 제71조의2" },
    ],
    crossReferences: [
      "상증법 제18조의2 (가업상속공제)",
      "상증법 시행령 제15조 (가업의 범위·피상속인 요건)",
      "상증법 시행령 제15조의2 (사후관리 5년)",
      "상증법 제71조 (연부연납 — 가업상속 20년 특례)",
      "상증법 제71조의2 (납부유예)",
      "상증법 시행령 별표 (가업상속공제 적용 업종)",
      "조특법 시행령 제27조의4 (가업승계 적용 업종)",
    ],
    taxAuthorityGuide: "국세청 '2024 가업승계 지원제도 안내' 책자 참조 (44쪽). 개인사업자·법인 모두 가업상속공제 가능. 증여세 과세특례는 법인 주식만.",
  },

  // ── 가업승계 증여세 과세특례 ──────────────────────────────
  {
    id: "gift_business_succession_special",
    version: "2026.1",
    lastUpdated: "2026-01-01",
    category: "gift",
    subcategory: "가업승계",
    savingType: "special_rate",
    targetAudience: ["heir", "business_owner"],
    name: "가업승계 증여세 과세특례",
    shortDescription: "생전 가업주식 증여 시 10억 공제 후 10~20% 특례세율",
    fullDescription: "18세 이상 거주자가 60세 이상 부모로부터 10년 이상 경영한 가업의 주식을 증여받을 때, 10억원 공제 후 120억까지 10%, 120억 초과분 20%의 특례세율을 적용합니다. 일반 증여세율(10~50%)보다 크게 유리. 한도는 경영기간에 따라 최대 600억원.",
    tags: ["가업승계", "증여세", "과세특례", "생전승계", "주식증여"],
    impactLevel: "very_high",
    maxDeductionAmount: 60_000_000_000,
    applicableRate: "120억 이하 10% / 120억 초과 20%",
    requirements: [
      { id: "req_1", description: "증여자(부모) 60세 이상", type: "age", value: "60세 이상", critical: true },
      { id: "req_2", description: "증여자 10년 이상 계속 경영", type: "period", value: "10년 이상", critical: true },
      { id: "req_3", description: "수증자 18세 이상 거주자", type: "age", value: "18세 이상", critical: true },
      { id: "req_4", description: "증여세 신고기한까지 가업 종사", type: "employment", critical: true },
      { id: "req_5", description: "증여일부터 3년 내 대표이사 취임", type: "period", value: "3년 이내", critical: true },
      { id: "req_6", description: "대표이사 취임 후 5년간 유지", type: "period", value: "5년", critical: true },
    ],
    conflicts: ["gift_startup_fund"], // 창업자금 특례와 중복 불가
    legalBasis: [
      { law: "조세특례제한법", article: "제30조의6", url: "https://www.law.go.kr/LSW//lsLawLinkInfo.do?lsJoLnkSeq=1001023551&lsId=001584&chrClsCd=010202", effectiveDate: "2026-01-01" },
    ],
    postManagement: {
      period: 5,
      requirements: [
        { item: "가업 유지", standard: "증여받은 가업 계속 영위, 1년 이상 휴·폐업 금지", penalty: "특례세율 취소, 일반세율로 재계산 추징" },
        { item: "지분 유지", standard: "증여받은 지분 유지", penalty: "처분 비율만큼 추징" },
        { item: "고용 유지", standard: "5년 통산 정규직 수·총급여액 90% 이상", penalty: "미달 비율만큼 추징" },
        { item: "대표이사", standard: "3년 내 취임, 취임 후 5년 유지", penalty: "특례 전액 취소" },
      ],
    },
    calculationParams: [
      { id: "gift_value", label: "증여 주식 가치", type: "number", unit: "원", required: true },
      { id: "parent_business_years", label: "부모 경영 기간", type: "number", unit: "년", min: 10, required: true },
      { id: "parent_age", label: "증여자(부모) 나이", type: "number", unit: "세", min: 60, required: true },
    ],
    calculationFormula: "과세표준 = 증여가액 - 10억. 120억 이하: 10%, 120억 초과: 20%. 일반 증여세와 비교하여 절세액 산출.",
    urgency: "long_term",
    difficulty: "expert",
    steps: [
      "부모 경영기간·나이 요건 확인",
      "가업 주식 가치 평가",
      "일반 증여 vs 과세특례 세액 비교 시뮬레이션",
      "증여세 과세특례 신청서 작성",
      "증여세 신고기한 내 신청",
      "3년 내 대표이사 취임 계획 수립",
      "5년 사후관리 체크리스트 수립",
    ],
    contentHook: {
      title: "생전 증여 vs 사후 상속, 100억 회사의 최적 선택은?",
      hook: "상속 대기하면 50%세율, 생전 증여하면 10%! 사후관리도 5년으로 단축!",
      targetKeyword: "가업승계 증여세 과세특례",
      estimatedViews: "high",
    },
    warnings: [
      "창업자금 증여세 과세특례와 중복 적용 불가",
      "증여세 신고기한까지 특례 신청하지 않으면 혜택 소멸",
      "사후관리(5년) 위반 시 일반세율로 재계산되어 가산세까지 부담",
    ],
    relatedItems: ["inheritance_business_deduction", "gift_startup_fund", "gift_family_exemption"],

    // ── 세무사 수준 정확성 데이터 (2026.4 딥리서치 검증) ──
    verification: {
      status: "self_checked",
      verifiedBy: "시스템 (국세청+법제처+KPMG+삼일PwC 교차 검증)",
      verifiedDate: "2026-04-04",
      notes: "조특법 제30조의6 확인. 법인 주식만 대상(개인사업자 불가). 사후관리 5년, 대표이사 3년 내 취임 확인.",
      nextReviewDate: "2026-07-01",
    },
    legalTexts: [
      {
        lawName: "조세특례제한법",
        articleNumber: "제30조의6",
        articleTitle: "가업의 승계에 대한 증여세 과세특례",
        fullText: "18세 이상인 거주자가 60세 이상의 부모로부터 10년 이상 계속하여 경영한 중소기업 또는 중견기업의 주식 또는 출자지분을 증여받는 경우 과세특례 적용.",
        keyProvisions: [
          "【대상】 법인 주식·출자지분만 가능 — 개인사업자 불가 (제1항)",
          "【증여자】 60세 이상 부모, 10년 이상 계속 경영, 최대주주 지분 40%↑(상장 20%) 10년↑ 보유 (제1항)",
          "【수증자】 18세 이상 거주자인 자녀 (제1항)",
          "【공제】 10억원 공제 후 과세 (제1항)",
          "【세율】 120억 이하 10%, 120억 초과분 20% (제1항) — 일반 증여세 10~50%보다 유리",
          "【한도】 10년↑ 300억, 20년↑ 400억, 30년↑ 600억 (제2항)",
          "【사후관리 5년】 (제6항, 2023.1.1 시행, 구법 7년)",
          "【대표이사 취임】 증여일부터 3년 내, 취임 후 5년 유지 (구법 5년 내) (제6항)",
          "【고용유지】 5년 통산 정규직수·총급여 90% 유지 (제6항)",
          "【업종유지】 중분류 내 변경 허용, 1년↑ 휴·폐업 금지 (제6항)",
          "【지분유지】 증여받은 지분 유지, 감소 시 추징 (제6항)",
          "【중복 불가】 창업자금 증여세 과세특례(제30조의5)와 중복 적용 불가",
          "【위반 시】 특례 취소 → 일반 증여세율(10~50%)로 재계산 + 가산세",
          "【증여 후 사망】 상속세 과세가액에 가산되나, 가업상속 요건 충족 시 상속공제도 가능",
        ],
        effectiveDate: "2026-01-01",
        lastAmendedDate: "2023-01-01",
        sourceUrl: "https://www.law.go.kr/LSW//lsLawLinkInfo.do?lsJoLnkSeq=1001023551&lsId=001584&chrClsCd=010202",
      },
    ],
    practicalCases: [
      {
        title: "100억 법인 — 생전 증여 vs 사후 상속 비교",
        situation: "60세 부친이 30년 운영한 100억 법인 주식을 35세 장남에게 승계",
        calculation: "증여세 과세특례: (100억-10억)×10% = 9억. 일반 증여세: 100억×50%-4.6억 = 45.4억. 절세: 36.4억",
        result: "과세특례로 36.4억 절세 (9억만 납부)",
        taxSaved: 36_400_000_000,
        source: "국세청 가업승계 지원제도 안내 (2024)",
      },
      {
        title: "200억 중견기업 — 특례 최대 활용",
        situation: "매출 1,000억 중견기업(주식 200억)을 장녀에게 생전 증여",
        calculation: "과세특례: (200억-10억) 중 120억×10%=12억 + 70억×20%=14억 = 26억. 일반: 약 90억",
        result: "약 64억 절세",
        taxSaved: 64_000_000_000,
      },
    ],
    faqs: [
      { question: "개인사업자도 증여세 과세특례 가능한가요?", answer: "불가합니다. 증여세 과세특례는 법인 주식·출자지분만 대상입니다. 개인사업자는 법인 전환 후 주식을 증여해야 합니다. 가업상속공제(상증법 제18조의2)는 개인사업자도 가능합니다.", legalBasis: "조특법 제30조의6 제1항" },
      { question: "3년 내 대표이사 취임 못 하면?", answer: "과세특례 전체가 취소되어 일반 증여세율(10~50%)로 재계산됩니다. 가산세도 부과. 반드시 3년 내 취임해야 합니다.", legalBasis: "조특법 제30조의6 제6항" },
      { question: "증여자(부모)가 사망하면 어떻게 되나요?", answer: "증여재산이 상속세 과세가액에 가산됩니다. 다만 가업상속 요건을 충족하면 가업상속공제(최대 600억)를 받을 수 있습니다.", legalBasis: "조특법 제30조의6 제8항" },
      { question: "창업자금 과세특례와 중복 적용 가능한가요?", answer: "불가합니다. 가업승계 증여세 과세특례(제30조의6)와 창업자금 과세특례(제30조의5)는 중복 적용이 안 됩니다.", legalBasis: "조특법 제30조의6 제1항 단서" },
    ],
    crossReferences: [
      "조특법 제30조의6 (가업승계 증여세 과세특례)",
      "조특법 시행령 제27조의6 (과세특례 세부요건)",
      "상증법 제18조의2 (가업상속공제 — 상속 시)",
      "조특법 제30조의5 (창업자금 과세특례 — 중복 불가)",
      "상증법 제47조 제2항 (증여 후 사망 시 상속세 합산)",
    ],
    taxAuthorityGuide: "국세청 '2024 가업승계 지원제도 안내' 참조. 생전 증여(조특법 제30조의6)는 법인만 가능하므로, 개인사업자는 법인 전환이 전제. 사후관리 5년 (2023.1.1 시행, 구법 7년).",
  },

  // ── 창업자금 증여세 과세특례 ──────────────────────────────
  {
    id: "gift_startup_fund",
    version: "2026.1",
    lastUpdated: "2026-01-01",
    category: "gift",
    subcategory: "창업자금",
    savingType: "special_rate",
    targetAudience: ["youth", "heir"],
    name: "창업자금 증여세 과세특례",
    shortDescription: "창업 목적 증여 시 5억 공제 후 10% 특례세율 (한도 50~100억)",
    fullDescription: "18세 이상 거주자가 60세 이상 부모로부터 중소기업 창업 목적으로 토지·건물 외 재산을 증여받을 때, 5억원 공제 후 10% 특례세율 적용. 한도 50억원 (10명 이상 신규고용 시 100억원).",
    tags: ["창업자금", "증여세", "과세특례", "중소기업", "스타트업"],
    impactLevel: "high",
    maxDeductionAmount: 10_000_000_000,
    applicableRate: "10% (5억 공제 후)",
    requirements: [
      { id: "req_1", description: "수증자 18세 이상", type: "age", value: "18세 이상", critical: true },
      { id: "req_2", description: "증여자(부모) 60세 이상", type: "age", value: "60세 이상", critical: true },
      { id: "req_3", description: "중소기업 창업 목적", type: "business_type", critical: true },
      { id: "req_4", description: "4년 내 창업자금 전액 사용", type: "period", value: "4년", critical: true },
      { id: "req_5", description: "토지·건물 제외한 재산", type: "asset", critical: true },
    ],
    conflicts: ["gift_business_succession_special"],
    legalBasis: [
      { law: "조세특례제한법", article: "제30조의5", url: "https://www.law.go.kr/LSW//lsLawLinkInfo.do?chrClsCd=010202&lsJoLnkSeq=900035485&lsId=001584", effectiveDate: "2026-01-01" },
    ],
    calculationParams: [
      { id: "gift_amount", label: "증여 금액", type: "number", unit: "원", required: true },
      { id: "new_employees", label: "신규 고용 예정 인원", type: "number", unit: "명", required: false },
    ],
    calculationFormula: "세액 = (min(증여액, 한도) - 5억) × 10%. 한도: 기본 50억, 10명↑ 고용 시 100억",
    urgency: "event_based",
    difficulty: "hard",
    steps: [
      "창업 업종 확인 (중소기업 해당 업종)",
      "부모로부터 현금/금융자산 증여",
      "증여세 과세특례 신청 (신고기한 내)",
      "4년 내 전액 창업자금으로 사용",
      "사용 내역 증빙 보관",
    ],
    contentHook: {
      title: "부모 돈으로 창업하면 세금 10%만! 100억까지 가능",
      hook: "부모님께 50억 받아 창업하면 세금 4.5억이면 끝!",
      targetKeyword: "창업자금 증여세 과세특례",
      estimatedViews: "medium",
    },
    relatedItems: ["gift_business_succession_special"],
    warnings: [
      "4년 이내 창업자금 전액 사용 의무 — 미사용 잔액은 일반 증여세 과세",
      "창업 후 10년 내 폐업·업종 변경 시 사후관리 과세 위험",
      "토지·건물은 대상 제외 — 현금·주식 등 비부동산 재산만 가능",
      "가업승계 과세특례(조특법 제30조의6)와 중복 불가",
    ],
    practicalCases: [
      {
        title: "부모로부터 20억 창업자금 증여",
        situation: "62세 부모, 25세 자녀에게 창업 목적으로 현금 20억원 증여",
        calculation: "과세표준 = 20억 - 5억(공제) = 15억 × 10% = 1.5억. 일반 증여세(최고 50%) 대비 약 8억 절감",
        result: "증여세 1억 5천만원 (일반 과세 시 약 9억원 대비 7억 5천만원 절감)",
        taxSaved: 750_000_000,
      },
    ],
  },

  // ── 증여 기본공제 ─────────────────────────────────────────
  {
    id: "gift_family_exemption",
    version: "2026.1",
    lastUpdated: "2026-01-01",
    category: "gift",
    subcategory: "증여공제",
    savingType: "deduction",
    targetAudience: ["all"],
    name: "증여재산공제 (10년 합산)",
    shortDescription: "배우자 6억, 직계존비속 5천만원 (미성년 2천만원) 공제",
    fullDescription: "10년간 합산하여 배우자 6억원, 직계존비속 5천만원(수증자 미성년 시 2천만원), 기타 친족 1천만원 공제. 혼인·출산 시 추가 1.5억 공제 (2024년~).",
    tags: ["증여공제", "배우자", "자녀", "증여세", "10년합산"],
    impactLevel: "high",
    maxDeductionAmount: 600_000_000,
    applicableRate: "배우자 6억 / 성년자녀 5천만 / 미성년자녀 2천만",
    requirements: [
      { id: "req_1", description: "10년 내 증여 합산", type: "period", value: "10년 단위", critical: true },
    ],
    legalBasis: [{ law: "상속세 및 증여세법", article: "제53조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "relationship", label: "증여자와의 관계", type: "select", options: [
        { label: "배우자", value: "spouse" },
        { label: "직계존비속 (성년)", value: "lineal_adult" },
        { label: "직계존비속 (미성년)", value: "lineal_minor" },
        { label: "기타 친족", value: "other_relative" },
      ], required: true },
      { id: "gift_amount", label: "증여 금액", type: "number", unit: "원", required: true },
      { id: "prior_gifts_10yr", label: "최근 10년 내 동일인 증여 합계", type: "number", unit: "원", defaultValue: 0, required: false },
    ],
    calculationFormula: "과세표준 = 증여가액 - 공제(배우자6억/성년5천만/미성년2천만) - 기공제분",
    urgency: "long_term",
    difficulty: "medium",
    steps: [
      "10년 내 기존 증여 이력 확인",
      "공제 한도 내 증여 계획 수립",
      "증여 후 3개월 내 증여세 신고",
    ],
    contentHook: {
      title: "증여세 0원으로 자녀에게 재산 물려주는 타임라인",
      hook: "10년 단위 5천만원씩, 30년이면 1.5억 무세!",
      targetKeyword: "증여세 면제 한도 2026",
      estimatedViews: "high",
    },
    warnings: [
      "10년 합산 규정 — 같은 증여자로부터 10년 내 모든 증여액이 합산되어 공제 한도 초과 시 과세",
      "증여 후 상속 발생 시 10년 이내 사전 증여재산은 상속세 과세가액에 합산",
      "미성년자 자녀에게 증여 시 공제 한도는 2천만원 (성년 시점과 미성년 시점 구분)",
      "증여세 신고 기한(3개월) 미준수 시 20% 무신고 가산세",
    ],
    practicalCases: [
      {
        title: "10년 단위 자녀 증여 플랜",
        situation: "30세 자녀에게 5천만원 증여, 이후 10년 후 추가 5천만원 증여 계획",
        calculation: "1차 5천만원 → 증여세 0원. 2차(10년 후) 5천만원 → 합산 0원. 총 1억원 무세 이전",
        result: "20년간 1억원 무세 이전 완료",
        taxSaved: 10_000_000,
      },
    ],
  },

  // ── 혼인·출산 증여공제 ────────────────────────────────────
  {
    id: "gift_marriage_birth",
    version: "2026.1",
    lastUpdated: "2026-01-01",
    category: "gift",
    subcategory: "혼인/출산",
    savingType: "deduction",
    targetAudience: ["newlywed", "parent"],
    name: "혼인·출산 증여재산공제",
    shortDescription: "혼인·출산 시 직계존속으로부터 추가 1.5억 공제",
    fullDescription: "2024년 1월 1일 이후 혼인신고 또는 자녀 출산(입양 포함) 시 직계존속으로부터 증여받는 재산에 대해 기존 5천만원과 별도로 추가 1억원 공제. 양가 합산 최대 1.5억원 추가 공제 가능 (총 2억원).",
    tags: ["혼인", "출산", "증여공제", "결혼자금"],
    impactLevel: "medium",
    maxDeductionAmount: 150_000_000,
    applicableRate: "추가 1억 (양가 합산 1.5억)",
    requirements: [
      { id: "req_1", description: "혼인신고 전후 2년 이내 증여", type: "period", value: "혼인신고 전후 2년", critical: true },
      { id: "req_2", description: "직계존속(부모, 조부모)으로부터 증여", type: "family", critical: true },
    ],
    legalBasis: [{ law: "상속세 및 증여세법", article: "제53조의2", effectiveDate: "2024-01-01" }],
    calculationParams: [
      { id: "gift_amount", label: "증여 금액", type: "number", unit: "원", required: true },
      { id: "event_type", label: "사유", type: "select", options: [
        { label: "혼인", value: "marriage" },
        { label: "출산", value: "birth" },
      ], required: true },
    ],
    calculationFormula: "추가 공제 1억 (기본 5천만 별도). 과세표준 = 증여액 - 5천만 - 1억",
    urgency: "event_based",
    difficulty: "easy",
    steps: [
      "혼인신고 또는 출산 시점 확인",
      "전후 2년 이내에 부모로부터 증여 실행",
      "증여세 신고 시 추가 공제 적용",
    ],
    contentHook: {
      title: "결혼하면 부모님께 2억까지 무세 증여 받을 수 있다!",
      hook: "양가 합산 최대 3억까지 세금 없이 결혼자금 마련!",
      targetKeyword: "혼인 증여공제 2026",
      estimatedViews: "high",
    },
    warnings: [
      "혼인신고 전후 2년 이내에 증여받아야 함 — 기간 초과 시 일반 증여세 과세",
      "직계존속(부모·조부모)만 해당 — 형제·고모 등 방계는 불가",
      "기존 10년 합산 증여공제(5천만)와 별도로 추가 1억 적용되므로 증여 계획 시 순서 중요",
    ],
    practicalCases: [
      {
        title: "혼인 시 양가로부터 증여",
        situation: "결혼 1개월 전, 친정 부모로부터 1억 5천만원, 시부모로부터 1억 5천만원 증여",
        calculation: "각각: 기본공제 5천만 + 혼인공제 1억 = 1억 5천만원까지 무세. 양가 합산 3억 전액 비과세",
        result: "총 3억원 무세 이전 (증여세 0원)",
        taxSaved: 30_000_000,
      },
    ],
  },

  // ── 상속세 자녀공제 확대 ──────────────────────────────────
  {
    id: "inheritance_child_deduction",
    version: "2026.1",
    lastUpdated: "2026-01-01",
    category: "inheritance",
    subcategory: "인적공제",
    savingType: "deduction",
    targetAudience: ["heir"],
    name: "상속세 자녀공제 (현행 5천만원)",
    shortDescription: "자녀 1인당 5천만원 공제 — 5억 확대안 국회 부결, 현행 유지",
    fullDescription: "상속세 자녀공제는 1인당 5천만원 (미성년자는 1천만원 × 잔여연수). 2025년 세법개정안에서 1인당 5억원으로 10배 확대하는 방안이 논의되었으나 국회에서 부결되어 현행 5천만원이 그대로 유지됨. 기초공제(2억)+인적공제 합계 vs 일괄공제(5억) 중 유리한 쪽 선택.",
    tags: ["상속세", "자녀공제", "인적공제", "상속공제"],
    impactLevel: "medium",
    maxDeductionAmount: 50_000_000, // 1인당 5천만원 (현행)
    applicableRate: "자녀 1인당 5천만원 (현행 유지)",
    requirements: [
      { id: "req_1", description: "상속인인 자녀 존재", type: "family", critical: true },
    ],
    legalBasis: [{ law: "상속세 및 증여세법", article: "제20조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "children_count", label: "상속인 자녀 수", type: "number", unit: "명", min: 1, required: true },
      { id: "estate_value", label: "총 상속재산 가액", type: "number", unit: "원", required: true },
    ],
    calculationFormula: "자녀공제 = 자녀수 × 5천만원. 기초공제(2억)+자녀공제 vs 일괄공제(5억) 중 큰 것 선택.",
    urgency: "event_based",
    difficulty: "medium",
    steps: [
      "상속인 구성 확인",
      "기초공제+인적공제 vs 일괄공제 비교",
      "유리한 공제 방식 선택",
    ],
    contentHook: {
      title: "상속세 자녀공제 5천만원 — 절세 전략 완전 분석 (2026)",
      hook: "자녀공제 5억 확대안 국회 부결! 현행 5천만원으로 최대한 절세하는 법",
      targetKeyword: "상속세 자녀공제 현행 2026",
      estimatedViews: "medium",
    },
    warnings: [
      "일괄공제(5억)와 기초+인적공제 중 유리한 방식 선택 — 자녀 4명 이상부터 인적공제가 일괄공제 초과",
      "자녀공제 5억 확대안 국회 부결 — 현행 5천만원 유지 (2026 현재), 향후 법 개정 여부 모니터링 필요",
      "미성년 자녀는 1천만원 × (19세까지 잔여연수)로 계산 — 단순 5천만원 아님",
    ],
    practicalCases: [
      {
        title: "자녀 3명 상속세 공제 비교",
        situation: "총 상속재산 20억원, 자녀 3명",
        calculation: "인적공제: 기초공제 2억 + 자녀 3명×5천만 = 3.5억. 일괄공제 5억 선택이 유리. 과세표준 20억-5억=15억",
        result: "일괄공제 선택으로 5억 공제, 상속세 절감",
        taxSaved: 100_000_000,
      },
    ],
  },
]
