// ============================================================
// 09-extra. 금융·투자 추가 절세 항목
// ============================================================
import type { TaxSavingItem } from "@/types/tax-database"

export const financialInvestmentExtra: TaxSavingItem[] = [
  {
    id: "fin_tax_free_savings",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "비과세종합저축",
    savingType: "exemption", targetAudience: ["senior", "all"],
    name: "비과세종합저축",
    shortDescription: "65세 이상·장애인 등 금융소득 5,000만원까지 비과세",
    fullDescription: "만 65세 이상, 장애인, 독립유공자 등이 가입 가능한 비과세종합저축. 1인당 합산 5,000만원 한도 내에서 이자·배당소득 전액 비과세.",
    tags: ["비과세종합저축", "65세", "장애인", "금융소득"],
    impactLevel: "medium", maxDeductionAmount: 50_000_000, applicableRate: "이자·배당 전액 비과세",
    requirements: [{ id: "r1", description: "만 65세 이상 또는 장애인 등", type: "age", value: "65세 이상", critical: true }],
    legalBasis: [{ law: "조세특례제한법", article: "제88조의2", effectiveDate: "2026-01-01" }],
    calculationParams: [{ id: "deposit", label: "저축 금액", type: "number", unit: "원", max: 50_000_000, required: true }],
    calculationFormula: "이자·배당 × 15.4% = 절세액", urgency: "year_round", difficulty: "easy",
    steps: ["자격 요건 확인 (65세↑, 장애인 등)", "은행에서 비과세종합저축 가입", "5,000만원 한도 내 예치"],
  },
  {
    id: "fin_rural_special_tax",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "농특세면제",
    savingType: "exemption", targetAudience: ["all"],
    name: "조합 출자금/예탁금 비과세",
    shortDescription: "농·수·신협 출자금 1,000만원, 예탁금 3,000만원까지 비과세",
    fullDescription: "농협, 수협, 신협, 새마을금고 등 조합에 출자금 1,000만원까지, 예탁금 3,000만원까지 이자소득 비과세. 금융소득 종합과세 대상에서도 제외.",
    tags: ["신협", "농협", "비과세", "예탁금", "출자금"],
    impactLevel: "low", applicableRate: "출자금 1,000만원 + 예탁금 3,000만원 비과세",
    requirements: [{ id: "r1", description: "조합원 가입", type: "other", critical: true }],
    legalBasis: [{ law: "조세특례제한법", article: "제89조의3", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "contribution", label: "출자금", type: "number", unit: "원", max: 10_000_000, required: false },
      { id: "deposit", label: "예탁금", type: "number", unit: "원", max: 30_000_000, required: false },
    ],
    calculationFormula: "비과세 이자 × 15.4% = 절세액", urgency: "year_round", difficulty: "easy",
    steps: ["조합(신협/농협 등) 가입", "출자금·예탁금 납입", "이자 비과세 자동 적용"],
  },
  {
    id: "fin_crypto_tax",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "가상자산",
    savingType: "deduction", targetAudience: ["investor"],
    name: "가상자산 양도소득 기본공제 (시행 여부 확인 필요)",
    shortDescription: "가상자산 양도소득 250만원 기본공제, 20% 과세",
    fullDescription: "가상자산 양도·대여소득에 대해 연 250만원 기본공제 후 20% 분리과세. 시행이 여러 차례 유예되어 현재 시행 상태 확인 필요. 취득가액 입증이 핵심.",
    tags: ["가상자산", "암호화폐", "비트코인", "양도소득", "20%"],
    impactLevel: "medium", maxDeductionAmount: 2_500_000, applicableRate: "250만원 공제 후 20%",
    requirements: [{ id: "r1", description: "가상자산 양도 또는 대여 소득 발생", type: "other", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제37조", effectiveDate: "시행 상태 확인 필요" }],
    calculationParams: [
      { id: "crypto_gain", label: "가상자산 양도차익", type: "number", unit: "원", required: true },
    ],
    calculationFormula: "세금 = max(양도차익 - 250만원, 0) × 20%", urgency: "year_end", difficulty: "medium",
    steps: ["취득가액 증빙 자료 보관", "양도차익 계산", "기본공제 250만원 적용", "소득세 신고 시 기타소득으로 신고"],
    warnings: ["시행 일자가 여러 차례 유예됨 — 최신 시행 상태 반드시 확인"],
    contentHook: { title: "비트코인 세금, 2026년에 정말 내야 하나? 총정리", hook: "250만원까지 비과세, 그 이상은 20% 세금!", targetKeyword: "가상자산 세금 2026", estimatedViews: "high" },
  },
  {
    id: "fin_stock_loss_offset",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "capital_gains", subcategory: "주식손실",
    savingType: "deduction", targetAudience: ["investor"],
    name: "주식 양도손실 통산",
    shortDescription: "같은 해 주식 양도이익과 양도손실 상계",
    fullDescription: "같은 과세연도 내 주식 양도 이익과 손실을 합산(통산)하여 순이익에만 과세. 대주주(특정 요건 해당 시) 및 해외주식 양도소득에 활용 가능.",
    tags: ["주식", "양도손실", "손익통산", "해외주식"],
    impactLevel: "high", applicableRate: "손실만큼 이익 상계",
    requirements: [{ id: "r1", description: "동일 과세연도 내 양도이익+양도손실 발생", type: "other", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제94조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "gain", label: "양도이익 합계", type: "number", unit: "원", required: true },
      { id: "loss", label: "양도손실 합계", type: "number", unit: "원", required: true },
    ],
    calculationFormula: "과세대상 = 양도이익 - 양도손실. 음수면 세금 0원.", urgency: "year_end", difficulty: "medium",
    steps: ["연내 양도이익/손실 정리", "손실 종목 연내 매도하여 이익과 상계", "양도소득세 확정신고 시 통산 반영"],
    contentHook: { title: "손실 난 주식, 팔아야 세금 아끼는 이유", hook: "수익 1천만원+손실 500만원 = 세금 절반으로!", targetKeyword: "주식 양도손실 통산", estimatedViews: "medium" },
  },
  {
    id: "fin_foreign_tax_credit",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "외국납부세액",
    savingType: "credit", targetAudience: ["investor"],
    name: "외국납부세액공제",
    shortDescription: "해외 투자소득에 대해 외국에서 낸 세금 공제",
    fullDescription: "해외주식 배당, 해외 부동산 소득 등에 대해 외국에서 이미 납부한 세금을 한국 세금에서 공제. 이중과세 방지. 공제한도는 국외소득이 전체소득에서 차지하는 비율만큼.",
    tags: ["외국납부세액", "해외주식", "이중과세", "세액공제"],
    impactLevel: "medium", applicableRate: "외국납부 세액 전액 (한도 내)",
    requirements: [{ id: "r1", description: "외국에서 세금 납부한 소득 존재", type: "other", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제57조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "foreign_tax", label: "외국 납부 세액", type: "number", unit: "원", required: true },
      { id: "foreign_income", label: "국외 소득", type: "number", unit: "원", required: true },
      { id: "total_income", label: "전체 종합소득", type: "number", unit: "원", required: true },
    ],
    calculationFormula: "공제한도 = 산출세액 × (국외소득/전체소득). 공제액 = min(외국납부세액, 한도)",
    urgency: "year_end", difficulty: "medium",
    steps: ["외국납부 세금 증빙 확인 (W-8BEN 등)", "종합소득세 신고 시 외국납부세액공제 신청"],
  },
  {
    id: "fin_nisa_savings",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "국내투자",
    savingType: "exemption", targetAudience: ["investor"],
    name: "국내투자형 ISA (NISA)",
    shortDescription: "국내 상장주식 투자 수익 비과세 (비과세 한도 확대)",
    fullDescription: "기존 ISA의 국내투자형 버전으로, 국내 상장주식 및 ETF 투자 수익에 대해 비과세 한도가 확대된 상품. 일반형 500만원, 서민형 1,000만원 비과세 (기존 ISA 대비 2.5배 확대 논의 중).",
    tags: ["NISA", "국내투자형ISA", "비과세", "국내주식"],
    impactLevel: "medium", applicableRate: "비과세 500~1,000만원 (확대 논의 중)",
    requirements: [{ id: "r1", description: "ISA/NISA 계좌 가입", type: "other", critical: true }],
    legalBasis: [{ law: "조세특례제한법", article: "개정 논의 중", effectiveDate: "2026 논의 중" }],
    calculationParams: [{ id: "invest_amount", label: "투자 금액", type: "number", unit: "원", required: true }],
    calculationFormula: "비과세 한도 내 투자수익 전액 비과세", urgency: "year_round", difficulty: "easy",
    steps: ["ISA/NISA 계좌 개설", "국내 상장주식/ETF 투자", "비과세 한도 확인"],
    warnings: ["국내투자형 ISA 세부 사항은 국회 확정 필요 — 최종안 확인 권장"],
  },
]
