// ============================================================
// 10-extra. 특수 상황 절세 추가 항목
// ============================================================
import type { TaxSavingItem } from "@/types/tax-database"

export const specialCasesExtra: TaxSavingItem[] = [
  {
    id: "special_rental_income",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "임대소득",
    savingType: "split", targetAudience: ["investor", "multi_home_owner"],
    name: "주택임대소득 분리과세 (2천만원 이하)",
    shortDescription: "주택임대수입 2천만원 이하 시 14% 분리과세 선택 가능",
    fullDescription: "주택임대수입 총 2천만원 이하인 경우 종합과세(6~45%)와 분리과세(14%) 중 유리한 방식 선택 가능. 분리과세 시 필요경비 60%(등록 시) 또는 50%(미등록) + 기본공제 400만원(등록)/200만원(미등록) 적용.",
    tags: ["임대소득", "분리과세", "종합과세", "주택임대"],
    impactLevel: "high", applicableRate: "14% 분리과세 vs 종합과세(6~45%)",
    requirements: [{ id: "r1", description: "주택임대수입 연 2천만원 이하", type: "income_limit", value: "2천만원 이하", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제64조의2", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "rental_income", label: "연 임대수입", type: "number", unit: "원", required: true },
      { id: "is_registered", label: "임대사업자 등록 여부", type: "boolean", required: true },
      { id: "other_income", label: "기타 종합소득", type: "number", unit: "원", required: true },
    ],
    calculationFormula: "분리과세: (수입-필요경비60%-기본공제400만) × 14%. 종합과세와 비교 후 선택.",
    urgency: "year_end", difficulty: "medium",
    steps: ["임대수입 2천만원 이하 확인", "분리과세 vs 종합과세 비교 시뮬레이션", "유리한 방식으로 종합소득세 신고"],
    contentHook: { title: "임대소득 세금, 14%면 끝? 종합과세와 비교 필수!", hook: "다른 소득 많으면 분리과세가 훨씬 유리!", targetKeyword: "주택임대소득 분리과세 2026", estimatedViews: "medium" },
  },
  {
    id: "special_severance_transfer",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "퇴직소득",
    savingType: "deferral", targetAudience: ["employee", "retiree"],
    name: "퇴직소득 연분연승 계산 특례",
    shortDescription: "장기 근속 시 퇴직소득세 경감 (연분연승법)",
    fullDescription: "퇴직소득세는 '연분연승법'으로 계산. 근속연수가 길수록 유리한 세율 적용. 퇴직금을 한꺼번에 받아도 근속연수로 나눈 후 세율 적용 → 다시 곱하므로 낮은 세율구간 적용.",
    tags: ["퇴직소득", "연분연승", "근속연수", "퇴직세"],
    impactLevel: "medium", applicableRate: "근속연수에 따라 실효세율 크게 감소",
    requirements: [{ id: "r1", description: "퇴직소득 발생", type: "other", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제55조의2", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "retirement_pay", label: "퇴직금", type: "number", unit: "원", required: true },
      { id: "service_years", label: "근속연수", type: "number", unit: "년", required: true },
    ],
    calculationFormula: "환산급여 = (퇴직금-비과세-근속공제) ÷ 근속연수 × 12. 환산세액 = 환산급여에 세율 적용 ÷ 12 × 근속연수.",
    urgency: "event_based", difficulty: "hard",
    steps: ["근속연수 정확히 계산", "퇴직소득공제 적용", "연분연승 방식으로 세액 산출"],
  },
  {
    id: "special_year_end_timing",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "타이밍전략",
    savingType: "deferral", targetAudience: ["sole_proprietor", "freelancer", "investor"],
    name: "소득/비용 귀속연도 조정 전략",
    shortDescription: "매출·비용 인식 시점을 조절하여 연간 세부담 평준화",
    fullDescription: "매출 인식 시점을 12월 vs 1월로 조정하거나, 비용 지출을 연말에 집중하여 당해 과세소득을 낮추는 전략. 사업자는 세금계산서 발행 시점, 대금 수령 시점 등을 활용.",
    tags: ["타이밍", "귀속연도", "연말", "비용인식"],
    impactLevel: "medium", applicableRate: "세율구간 변동분만큼 절세",
    requirements: [{ id: "r1", description: "사업소득 또는 기타소득 존재", type: "income_limit", critical: false }],
    legalBasis: [{ law: "소득세법", article: "제39조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "current_income", label: "올해 예상 소득", type: "number", unit: "원", required: true },
      { id: "next_year_income", label: "내년 예상 소득", type: "number", unit: "원", required: true },
    ],
    calculationFormula: "올해 소득이 세율구간 경계 부근이면, 매출 이연 또는 비용 앞당김으로 절세",
    urgency: "year_end", difficulty: "medium",
    steps: ["올해·내년 소득 추정", "세율구간 경계 확인", "매출/비용 타이밍 조정", "증빙 일자 관리"],
    contentHook: { title: "연말에 이것만 하면 세금이 달라진다! 타이밍 절세법", hook: "12월 31일 vs 1월 1일, 하루 차이로 수십만원 절세!", targetKeyword: "연말 절세 타이밍", estimatedViews: "medium" },
  },
  {
    id: "special_nontaxable_allowance",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "비과세소득",
    savingType: "exemption", targetAudience: ["employee"],
    name: "비과세 근로소득 총정리",
    shortDescription: "식대 20만, 자가운전 20만, 야간근로수당 등 비과세",
    fullDescription: "근로소득 중 비과세 항목: 식대(월 20만원), 자가운전보조금(월 20만원), 연구보조비(월 20만원), 생산직 야간근로수당·연장수당(연 240만원), 출산보육수당(자녀당 월 20만원), 학자금, 국외근무수당(월 100~300만원) 등.",
    tags: ["비과세", "식대", "야간수당", "자가운전", "근로소득"],
    impactLevel: "medium", applicableRate: "각 항목별 월 한도",
    requirements: [{ id: "r1", description: "근로소득자", type: "employment", critical: true }],
    legalBasis: [{ law: "소득세법", article: "제12조", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "meal_allowance", label: "식대 (월)", type: "number", unit: "원", required: false },
      { id: "car_allowance", label: "자가운전보조금 (월)", type: "number", unit: "원", required: false },
    ],
    calculationFormula: "비과세 합계 × 한계세율 = 절세 효과", urgency: "year_round", difficulty: "easy",
    steps: ["현재 급여에서 비과세 항목 분리 현황 확인", "누락된 비과세 항목 인사팀에 요청", "급여명세서에 비과세 항목 별도 표시 확인"],
    contentHook: { title: "월급에서 빠지는 세금, 이렇게 줄이세요! 비과세 총정리", hook: "식대+교통비+보육수당, 연 720만원까지 비과세!", targetKeyword: "비과세 근로소득 항목 2026", estimatedViews: "high" },
  },
  {
    id: "special_tax_saving_products",
    version: "2026.1", lastUpdated: "2026-01-01",
    category: "income", subcategory: "절세상품",
    savingType: "exemption", targetAudience: ["all"],
    name: "절세 금융상품 포트폴리오",
    shortDescription: "ISA + 연금저축 + IRP + 청년펀드 조합으로 최대 절세",
    fullDescription: "절세 금융상품을 조합하여 최대 절세 효과: 연금저축(600만원) + IRP(합산 900만원) 세액공제 148만원, ISA(비과세 200~400만원), 청년형장기펀드(소득공제 240만원). 총 연간 약 400만원 이상 절세 가능.",
    tags: ["절세상품", "포트폴리오", "ISA", "연금저축", "IRP"],
    impactLevel: "high", maxSavingAmount: 4_000_000, applicableRate: "상품 조합 시 연 400만원+",
    requirements: [{ id: "r1", description: "각 상품 가입 가능 요건 충족", type: "other", critical: false }],
    legalBasis: [{ law: "소득세법·조세특례제한법", article: "각 상품별 근거", effectiveDate: "2026-01-01" }],
    calculationParams: [
      { id: "pension", label: "연금저축 납입", type: "number", unit: "원", required: false },
      { id: "irp", label: "IRP 납입", type: "number", unit: "원", required: false },
      { id: "isa", label: "ISA 납입", type: "number", unit: "원", required: false },
    ],
    calculationFormula: "연금저축+IRP 세액공제 + ISA 비과세 + 기타 상품 효과 합산",
    urgency: "year_round", difficulty: "easy",
    steps: ["현재 가입 상품 현황 점검", "누락된 상품 신규 가입", "연 납입 계획 수립", "자동이체 설정"],
    contentHook: { title: "연 400만원 절세하는 금융상품 조합 공개!", hook: "이 4가지만 가입하면 매년 400만원 돌려받습니다!", targetKeyword: "절세 금융상품 조합 2026", estimatedViews: "high" },
  },
]
